### ISSUE TITLE
Check garbage collection

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/make-a-ten#131]
Require.js seems to leak memory, but probably not at a fast enough rate to cause a problem.

Seems to be filled with "other", so I'm curious what's going on.

**Comment by jonathanolson** [comment]
I've matched all listeners so it shouldn't leak memory. In a 30-minute run, it stayed in the 30-34 MB range.

**Comment by samreid** [comment]
<img width="210" height="252" alt="Image" src="https://github.com/user-attachments/assets/ecd3cd90-2c25-4363-91e7-0fa9f3ae2ae9" />
