### ISSUE TITLE
The opacity of the paper numbers should not change dynamically

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/make-a-ten#134]
If the sim sees a paper number is over another, it is somewhat transparent:
![making-tens-transparent](https://cloud.githubusercontent.com/assets/480878/13419978/9f6da10a-df3f-11e5-9e10-08eb18dc7b65.PNG)

However if it's in the front (and due to a bug in the code, this really only happens for a single paper in the very front), it's opaque:
![making-tens-opaque](https://cloud.githubusercontent.com/assets/480878/13420000/c07a8cdc-df3f-11e5-9052-b05a4c006373.PNG)

So, do we want varying opacity? Having everything set at the "transparent" option looks pretty good to me. Paper doesn't change in property based on what it's over.

If we do want it to vary, I'll submit issues to fix it, otherwise I'll submit an issue to make it constant.

@amanda-phet and @bethstade, opinions?

**Comment by jonathanolson** [comment]
For reference (due to the bug), here's an opaque 10 next to a transparent 10:
![making-tens-transparency](https://cloud.githubusercontent.com/assets/480878/13420058/263e73ee-df40-11e5-93d6-ef09f982936d.PNG)

**Comment by jonathanolson** [comment]
Note to my future self: relevant code is in MakingTensCommonView step(). Code does not make paper numbers "opaque" again after they are transparent.

**Comment by bethstade** [comment]
This seems like an incomplete fix to an earlier issue with changing opacity.
Yes, should always be transparent.

**Comment by jonathanolson** [comment]
@AshrafSharf, can we change the opacity of the paper number nodes to be constant, instead of sometimes being opaque?

**Comment by jonathanolson** [comment]
Additionally, it seems that paper slips that are part of one number also vary in opacity (e.g. the 100 in 111 is more opaque than the 10). @bethstade, was this desired? I'd consider trying "every paper slip has the same transparency" first to see if it looks acceptable.

**Comment by bethstade** [comment]
that makes sense
