### ISSUE TITLE
Casting NumberEntryControl's value in KeyBoardPanel

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/make-a-ten#145]
It seems nice to immediately cast the NumberEntryControl's value to a number before passing elsewhere. This would allow all of the other casts to numbers to go away.

Additionally, parseInt should be the preferred way to turn the string into a number.

**Comment by AshrafSharf** [comment]
The NumberKeyPad which is from Scenery Phet uses string to display digits. So only when value is set to NumberKeyPad it is translated to and from string. In all other places it is either null or a number.

**Comment by jonathanolson** [comment]
I still see a numeric cast in PaperNumberModel's changeNumber, is that unrelated?
