### ISSUE TITLE
Explore screen should have limited numbers

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/make-a-ten#151]
I was able to drag out over 9999 in total numbers, and they error (expectedly) when you try to combine them:

![screen shot 2016-03-01 at 1 41 02 pm](https://cloud.githubusercontent.com/assets/480878/13441202/4ddd2044-dfb3-11e5-8478-20e3fcab91f9.png)

@amanda-phet and @bethstade, can you comment on whether 9999 is the maximum? Presumably the numbers that can't be pulled out (below in the panel) should be disabled. I vaguely remember this discussed during the design.

**Comment by amanda-phet** [comment]
Jon that's correct that you should not be able to do this. Once the total reaches a point where a new number would push it over 9999, that number should become disabled in the panel. I thought this was working at one point so I'm not sure what happened.

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Tue, Mar 1, 2016 at 12:43 PM -0800, "Jonathan Olson" <notifications@github.com<mailto:notifications@github.com>> wrote:


I was able to drag out over 9999 in total numbers, and they error (expectedly) when you try to combine them:

[screen shot 2016-03-01 at 1 41 02 pm]<https://cloud.githubusercontent.com/assets/480878/13441202/4ddd2044-dfb3-11e5-8478-20e3fcab91f9.png>

@amanda-phet<https://github.com/amanda-phet> and @bethstade<https://github.com/bethstade>, can you comment on whether 9999 is the maximum? Presumably the numbers that can't be pulled out (below in the panel) should be disabled. I vaguely remember this discussed during the design.

-

**Comment by jonathanolson** [comment]
Implemented. Disabling by lowering opacity (the usual method) didn't really look great. Making them disappear fully seems to work much better.

Let me know if that works, or if I should make changes.

**Comment by bethstade** [comment]
<img width="1198" alt="screen shot 2016-10-28 at 11 37 14 am" src="https://cloud.githubusercontent.com/assets/5370001/19816082/03c817bc-9d03-11e6-8ee3-4144a4b4c4f5.png">
I am still able to get over 10,000

**Comment by bethstade** [comment]
<img width="1260" alt="screen shot 2016-10-28 at 11 38 02 am" src="https://cloud.githubusercontent.com/assets/5370001/19816101/2b14df6c-9d03-11e6-811c-a83ea2e8cc4b.png">
Also tried to put a 500 on 9500, the 500 is resting on the 9500 and then the screen froze.

**Comment by jonathanolson** [comment]
For up-to-date testing however, please use http://phettest.colorado.edu/make-a-ten/make-a-ten_en.html?ea&brand=phet if you are on campus.

**Comment by jonathanolson** [comment]
Also launching with a 9700 (http://phettest.colorado.edu/make-a-ten/make-a-ten_en.html?ea&brand=phet&exploreNumbers=9700) makes testing this easier.

**Comment by bethstade** [comment]
great. that is a big help.  I thought I had the right version when I was on campus?  It seemed to be the new version. Will try again on Monday with the link you recommended.

**Comment by amanda-phet** [comment]
This is looking good to me. I like that the last numbers are removed from the number panel. @bethstade once you have looked it over I think you can close this issue.

**Comment by bethstade** [comment]
do we have a current dev version?


----- Original Message -----From: Amanda McGarry <notifications@github.com>To: phetsims/make-a-ten <make-a-ten@noreply.github.com>Cc: bethstade <stadee@colorado.edu>, Mention <mention@noreply.github.com>Sent: Tue, 01 Nov 2016 20:56:52 -0000 (UTC)Subject: Re: [phetsims/make-a-ten] Explore screen should have limited numbers (#151)

This is looking good to me. I like that the last numbers are removed from the number panel. @bethstade once you have looked it over I think you can close this issue.
&mdash;You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jonathanolson** [comment]
http://www.colorado.edu/physics/phet/dev/html/make-a-ten/1.0.0-dev.8/make-a-ten_en.html is a snapshot of the current code.

**Comment by bethstade** [comment]
looks great.
