### ISSUE TITLE
PaperNumberModel's decomposeIntoBaseNumbers

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/make-a-ten#154]
We shouldn't need to resort to strings to extract both the digits and their powers. Can this be rewritten using mod (%), Math.pow and dot's Util.log10?

For a specific place (0 meaning singles digit, 1 for tens, etc.):
```js
var digit = Math.floor( x / Math.pow( 10, place ) ) % 10;
var baseNumber = digit * Math.pow( 10, place );
```

**Comment by AshrafSharf** [comment]
Code changed as recommended except for
calculating the number of digits( ``` var noOfDigits = (value + '').length;```)
