### ISSUE TITLE
Ordering of base numbers and indices

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/make-a-ten#155]
The current ordering seems to be:
- 1 digit in length? 0 => 1s place
- 2 digits in length? 0 => 10s place, 1 => 1s place
- 3 digits in length? 0 => 100s place, 1 => 10s place, 2 => 1s place
- 4 digits in length? 0 => 1000s place, 1 => 100s place, 2 => 10s place, 3 => 1s place

Additionally, things are indexed off of the position of the largest base number it seems, thus why TWO_DIGIT_OFFSET_DIMENSIONS[1] - TWO_DIGIT_OFFSET_DIMENSIONS[0] = THREE_DIGIT_OFFSET_DIMENSIONS[2] - THREE_DIGIT_OFFSET_DIMENSIONS[1], etc.

This adds a lot of additional code and constants, and I'd propose that things should be indexed in a more standard way, based on Math.pow( 10, n ). Thus:
- 0 => 1s place, 1 => 10s place, 2 => 100s place, 3 => 1000s place (as always, when they exist).

Additionally, instead of four different offset dimensions, you only need one.

This also simplifies many computations, where you don't have to handle each digit-length separately.

**Comment by jonathanolson** [comment]
This would presumably also affect BaseNumber.

**Comment by jonathanolson** [comment]
I also have a note that potentially considering having the model position in the center-right (so it doesn't change as digits are added/removed) may be beneficial.

**Comment by AshrafSharf** [comment]
@jonathanolson for a three digit number 107, we only need 2 images 100 and 7, similarly for 4 digit number 1070, we need only 2 images. I am not clear if the Math.pow base generic logic would address these scenarios. Please advice

**Comment by jonathanolson** [comment]
I'm not sure I understand how reordering indices would affect logic about how many images we need. Plan to discuss on a call?
