### ISSUE TITLE
paperNumberNodeLayer handling

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/make-a-ten#159]
It seems this is created in every subtype of screen view, and passed into the common view?

Usual convention is that the common screen view creates nodes used for layering (i.e. MakingTensCommonView would create paperNumberNodeLayer), and then it would provide other layers that the subtypes (e.g. MakingTensGameScreenView) can add content to.

This also means the paperNumberNodeLayer doesn't have to be created in three places and passed through constructors.

**Comment by AshrafSharf** [comment]
paperNumberNodeLayer  is created by MakingTensCommonView  and subtypes add them at the right position.They are not passed through constructors now.
