### ISSUE TITLE
Mouse and touch areas

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/make-a-ten#16]
It would be great to have mouse and touch areas defined at least for the paper pieces, both so that we can pass the query parameter ?showPointerAreas to visualize the areas, but also so that we can extend the touch areas past where the mouse areas are (so things are easier to touch).

This also applies to things like the "Hide Total" checkbox (and others), which can have a much larger touch area.

**Comment by AshrafSharf** [comment]
Have added Mouse and Touch Areas to PaperNumberNode
The Hide Total Check Box's touch Area is also dilated.

![image](https://cloud.githubusercontent.com/assets/8498160/9597753/95c48578-50a2-11e5-998c-b261e12ff955.png)

**Comment by jonathanolson** [comment]
@ariel-phet, for touch areas to be extended outside of the paper pieces themselves, we'd probably want a solution like in Pendulum Lab (if a touch is over the background, see if it's closest paper piece is within a certain distance, and if so start a drag like it was over that paper piece).

Is that desired, or can/should we just leave the touch areas covering the paper itself (not expanding further)? If we just normally expanded touch areas, you'd get overlapping problems, e.g. "I'm pressing on paper A, but paper B is in front of A and close enough to our finger that it is getting dragged instead".

**Comment by jonathanolson** [comment]
Also @AshrafSharf, we'll want to discuss input handling approaches in general for PaperNumberNode, specifically for the custom behavior needed here, how to handle cursors, etc.

**Comment by ariel-phet** [comment]
@jonathanolson Yes I think we would go with the pendulum lab solution, not expanding touch areas more than the paper. Back to you.

**Comment by jonathanolson** [comment]
@AshrafSharf, at your convenience this would be good to discuss with other input-related issues during meetings.

We'll want a solution similar to how PendulumLab uses ClosestDragListener.

**Comment by jonathanolson** [comment]
> @jonathanolson Yes I think we would go with the pendulum lab solution, not expanding touch areas more than the paper. Back to you.

@ariel-phet, I just realized I'm not sure what you are recommending (included features from both), can you clarify:

1. Pendulum-lab solution where the touch areas extend beyond the paper numbers themselves, and it picks the closest paper number hit area.
2. Leave touch areas as they are now (same as mouse areas, they do NOT extend beyond the paper numbers).

**Comment by ariel-phet** [comment]
@jonathanolson I was going off of your comment https://github.com/phetsims/make-a-ten/issues/16#issuecomment-184867729

**Comment by ariel-phet** [comment]
So @jonathanolson please review the comment you made, and use your best judgement as to a solution.

**Comment by jonathanolson** [comment]
Added behavior as described, where touches close to numbers can move or pull off. @amanda-phet, are you able to test?

**Comment by amanda-phet** [comment]
I like it.
