### ISSUE TITLE
PaperImageCollection

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/make-a-ten#161]
Seems like this should be in the view folder instead of the model (deals with images, and it's exclusively used by the view).

Second, if it's not a type (just a collection of functions or constants), there's no need to use inherit. So instead of:
```js
  function PaperImageCollection() {

  }

  return inherit( Object, PaperImageCollection, {},
    //statics
    {
      /**
       *
       * @param {number} number
       * @returns {ImageNode}
       */
      getNumberImage: function( number ) {
        return allImages[ number ];
      }
    } );
```
that could be rewritten as:
```js
  return {
    /**
     *
     * @param {number} number
     * @returns {ImageNode}
     */
    getNumberImage: function( number ) {
      return allImages[ number ];
    }
  };
```

Third, for efficiency reasons, it would be beneficial for PaperImageCollection to create actual scenery Image objects, so that usages (like in PaperNumberNode) would only need to add the images, not create new Image nodes.

**Comment by jonathanolson** [comment]
Additionally, you could get rid of the getNumberImage function and put the images on the object directly, so that clients only need to do ```PaperImageCollection[ number ]```.

**Comment by AshrafSharf** [comment]
PaperNumberCollection now doesn't use Inherit.

Image Node's position within a paper Number are directly manipulated.Storing imageNodes directly makes the work by reference which is causing problem. Moving one imageNode within a PaperNumber (say image corresponding to 2 in a number 102) affects other 2 elsewhere.
So I haven't implemented the other recommendation of caching imageNodes directly in paperNumberCollection
