### ISSUE TITLE
Duplication of StartGameLevelNode

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/make-a-ten#166]
I see area-builder, balancing-act and making-tens. Looks like we should have some common code support for this. @jbphet, are you available to provide an opinion on this?

Issues that relate to this file: https://github.com/phetsims/making-tens/issues/165, https://github.com/phetsims/making-tens/issues/116, https://github.com/phetsims/making-tens/issues/86, https://github.com/phetsims/making-tens/issues/79 and particularly https://github.com/phetsims/making-tens/issues/128.

I'm going to hold off of further code review of this file (and recommended changes) for now.

**Comment by jbphet** [comment]
Having common code support for this makes sense.  There's even a comment in Area Builder version that says:

> TODO: This was copied from Balancing Act, used for fast proto, should be replaced with generalized version.

So there you have it.  Now we just have to figure out who should do it.  Maybe @AshrafSharf can make a first pass at it.

**Comment by jonathanolson** [comment]
@AshrafSharf, would you be comfortable creating an equivalent to StartGameLevelNode in our common code that is used by making-tens, area-builder and balancing-act?

**Comment by jonathanolson** [comment]
(Doing initial work in branches would be fine)

**Comment by jonathanolson** [comment]
There looks to be a LOT of differences here between the five:

- area-builder
- balancing-act
- build-an-atom
- expression-exchange
- make-a-ten

except that area-builder's and expression-exchange's are almost identical.

I really don't have much experience with vegas yet, @jbphet, do you think there are things in StartGameLevelNode that can be factored out for all games, or is this something where we should just have a template that each sim starts with (due to needed customizations)?

**Comment by jbphet** [comment]
I'll spend a little time thinking about this and will propose something for discussion at the next developer meeting.

**Comment by jbphet** [comment]
We discussed this in the 10/20/2016 developer meeting and decided that the amount of code is small enough and the behavior is different enough that it isn't a good use of our time to try to generalize the level selection screen.  Closing.
