### ISSUE TITLE
PaperNumberCreatorNode's addShapeToModel

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/make-a-ten#169]
Does this relate to shapes in any way? It seems more akin to PaperNumberNode's addNumber/addNumberToModel callback (currently named addNumberModelCallBack).

Do these two differently-named functions do the same thing, and if so, can they have the same name?

**Comment by jonathanolson** [comment]
Also see renaming for combineNumbersIfApplicableCallback

**Comment by jonathanolson** [comment]
canPlaceShape also seems to not deal with Shape(s). Is this better as canPlaceNumber?

**Comment by AshrafSharf** [comment]
Fixed as part of addressing issues  #207 , #160
