### ISSUE TITLE
MakingTensSharedConstants.EXPLORER_SCREEN_BACKGROUND_COLOR

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/make-a-ten#174]
It's the "Explore" screen, so this should be named ```MakingTensSharedConstants.EXPLORE_SCREEN_BACKGROUND_COLOR``` (explore, not explorer).

**Comment by jonathanolson** [comment]
Similarly, addUserCreatedNumberModelToExplorerView => addUserCreatedNumberModelToExploreView, although per other recommendations, this would presumably be able to be renamed addUserCreatedNumber.

**Comment by AshrafSharf** [comment]
EXPLORER_SCREEN_BACKGROUND_COLOR  renamed to EXPLORE_SCREEN_BACKGROUND_COLOR
addUserCreatedNumberModel renamed as part of #207
