### ISSUE TITLE
MakingTensExploreScreenView's canPlaceShape

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/make-a-ten#176]
It doesn't deal with shapes. Presumably this should be renamed to something like ```canPlaceNumber```, or since it includes a position, ```canPlaceNumberAt```?

**Comment by jonathanolson** [comment]
Additionally, why is there a scale factor of 0.3 here?:
```js
      var widthPart = paperNumberBounds.width * 0.3;
      var heightPart = paperNumberBounds.height * 0.3;
```

**Comment by AshrafSharf** [comment]
The method name "canPlaceShape" is renamed to "canPlaceNumberAt"

___purpose of scale factor___
This method is used to determine if the user has placed the picked number sufficiently away from
the container panel. if not the number has to be returned back to the container itself.
It does the check by intersecting the bounds of container with the dynamic bounds  created using the dropped position and dimension of the paperNumber.
How far away the user has to drop the number varies with the size of the paper number
