### ISSUE TITLE
Dropped numbers returning to the explore panel seem to go "past" the vertical center

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/make-a-ten#186]
When dropping numbers pack into the panel, numbers seem to go past the center of their equivalents in the panel (downwards) until they are decently off-screen (until they disappear).

Hard to screenshot, but here's an attempt:
![making-tens-drop](https://cloud.githubusercontent.com/assets/480878/13475748/c930e7fc-e081-11e5-9ea9-828b029fb20a.PNG)

@amanda-phet and @bethstade, I would expect that the number would disappear once it got to the "center" of its original place (e.g. a 10 would disappear when centered over the 10 in the panel).

**Comment by bethstade** [comment]
Can't remember if we specified this exactly. I think the bigger concern was that numbers didn't accidentally "fall in," hence they need to be half in the box to "go away."  But, the 10 disappearing when centered over the 10 makes sense and is perhaps a good modification.

**Comment by jonathanolson** [comment]
> I think the bigger concern was that numbers didn't accidentally "fall in," hence they need to be half in the box to "go away." But, the 10 disappearing when centered over the 10 makes sense and is perhaps a good modification.

https://github.com/phetsims/making-tens/issues/184 handles this issue (it's actually the opposite, on the 1st drag, numbers can be more than halfway outside the panel and STILL be treated as if they were dropped in the panel).

This issue is specifically for the fact that once numbers have been dropped in the panel (somehow, doesn't matter), the pieces of the number animate to **well below** their "original" positions before disappearing.
