### ISSUE TITLE
Recommend alternate way of accomplishing returnedToOrigin in PaperNumberModel

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/make-a-ten#213]
The initial position is currently checked to see if a number has returned:
```js
      // The shape will be removed from the model if and when it returns to its origination point.  This is how a shape
      // can be 'put back' into the panel.
      paperNumberModel.on( 'returnedToOrigin', function() {
        if ( !paperNumberModel.userControlled ) {
          // The shape has been returned to the panel.
          self.residentNumberModels.remove( paperNumberModel );
        }
      } );
```
and if so (on the explore screen) this triggers its removal from the model (if user controlled):
```js
      // The shape will be removed from the model if and when it returns to its origination point.  This is how a shape
      // can be 'put back' into the panel.
      paperNumberModel.on( 'returnedToOrigin', function() {
        if ( !paperNumberModel.userControlled ) {
          // The shape has been returned to the panel.
          self.residentNumberModels.remove( paperNumberModel );
        }
      } );
```

This leads to cases where:
1. User pulls off a fresh number from an existing number (its initial position is NOT in the panel)
2. User tries to combine it with another number (which won't combine)
3. Number repels away, but goes over its origin position and is instantly removed from the model.

It also requires the userControlled condition in the returnedToOrigin listener (whose reason for existence is not documented), as otherwise things would be very buggy.

Instead of handling this by detecting if the number has returned to its origin, I'd recommend explicitly handling this in addUserCreatedNumberModelToExplorerView (MakingTensExploreScreenView) when a number's animation back has completed (see https://github.com/phetsims/making-tens/issues/157)

**Comment by AshrafSharf** [comment]
@jonathanolson As you have described, I am able to reproduce the issue. I also don't see any standard way of invoking a callback once returnToOrigin animation is finished.
So instead of checking userControlled variable, can I set  a explicit variable - 'removeOnReturnToOrigin"  and handle this issue? Please suggest.
