### ISSUE TITLE
New arrow cues

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/make-a-ten#231]
The arrow cues should look like this:
![screen shot 2016-10-10 at 10 15 48 am](https://cloud.githubusercontent.com/assets/7852916/19242913/92d01d18-8ed2-11e6-9f1d-da8e051d1be0.png)

The hand is from atomic interactions. The arrows should be drawn in code. The blue color is the same as the blue "sum" text. 

Specifications: 
- There are two cues: a "move" cue and a "pull apart" cue. 
- On the explore screen, the sim starts up with a 10 in the play space with both cues present.
- If another piece is put in the play space, the cues jump to that new piece. 
- The cues behave separately: once a piece has been moved, the move cue fades. Once a piece has been pulled apart, the pull apart cue fades. When the cues fade, there should be a slight delay after the action happens (so for instance if you drag out a 10, then drag out a 100 and then switch back to dragging the 10, the both cues would jump to the 10 and then the move cue would fade). 
- The cues never reappear unless reset all is clicked. 
- The move cue can appear on a 1, 10, or 100. The move cue is on whatever piece is most recently touched.
- The pull apart cue is on most recent piece that can be split apart (10 or 100, not 1). 
- Reset all makes both cues reappear.

We would also like to have a query parameter that starts the sim with a blank play area (so, it would not start up with a 10 in the play space with both arrow cues).

**Comment by jonathanolson** [comment]
@amanda-phet, how can I get the artwork for the cues?

**Comment by amanda-phet** [comment]
What artwork would you like to have? The hand is the same one from Atomic Interactions, which I believe was drawn in code. I'm happy to make a .png if you would prefer that. Would you also like the arrows to be part of the artwork, or are those better to have in code?

**Comment by jonathanolson** [comment]
Ahh, didn't know the hand was used before. It sounds good for me to use that and generate the arrows. Thanks!

**Comment by jonathanolson** [comment]
Will migrate from SOM repo. CM noted to migrate the asset also (not just the image to scenery-phet/images).

**Comment by jonathanolson** [comment]
Added query parameter ```?exploreNumbers```, whose value is a list of initial numbers, e.g. ```?exploreNumbers=10,51``` will show a 10 and 51. Currently use ```?exploreNumbers=0``` for no numbers, as 0s are ignored.

@samreid, is there a way to have ```?exploreNumbers=``` return an empty array with QueryStringMachine, instead of an error? See ```MakeATenExploreModel.addInitialNumbers()```.

**Comment by jonathanolson** [comment]
Implemented cues basically as described, with the following notes:

1. Easier to initially implement circular curve in the 'pull apart' cue. If elliptical curve is desired, it should be possible (let me know).
2. If cues are on a number that disappears for other reasons (e.g. dragged to the explore panel), the cue disappears until the next valid target is interacted with. Then it can re-appear until it is used. I interpreted "The cues never reappear unless reset all is clicked." to mean faded cues never reappear, but it's an easy change to prevent cues from reappearing (e.g. user drags intial 10 into panel, then drags out 100. currently a pull-apart cue appears, but we can make it not appear).
3. When two numbers are combined (e.g. user drags a 10 onto a 100), the split cue will move to the combined result (e.g. 110). It just felt weird to disappear otherwise.
4. Cues can show up on any valid paper number (1 not valid for pull-apart), instead of the quoted "The move cue can appear on a 1, 10, or 100.". I presume having move cues on a 90 (say the user starts dragging it) is desired, but I can easily limit the cue to only appear on those numbers if desired.

Please give it a try, and see what feels weird (and what should be changed).

**Comment by jonathanolson** [comment]
Also, I'm aware the initial 10 can't be dragged into the panel to make it disappear. It's related to https://github.com/phetsims/make-a-ten/issues/243 caused by https://github.com/phetsims/make-a-ten/issues/213, and I'll have it fixed soon.

**Comment by bethstade** [comment]
Can I access the new version when I am on campus this morning?


----- Original Message -----From: Jonathan Olson <notifications@github.com>To: phetsims/make-a-ten <make-a-ten@noreply.github.com>Cc: bethstade <stadee@colorado.edu>, Mention <mention@noreply.github.com>Sent: Fri, 28 Oct 2016 08:33:13 -0000 (UTC)Subject: Re: [phetsims/make-a-ten] New arrow cues (#231)

Assigned #231 to @bethstade.
&mdash;You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by samreid** [comment]
@jonathanolson I'm happy to discuss it, but my instinct on seeing a url like:

`http://my.url.com/sim.html?exploreNumbers=&otherQueryString`
or
`http://my.url.com/sim.html?exploreNumbers=`

is that they look like syntax errors.

Would it be acceptable to use:
`http://my.url.com/sim.html?otherQueryString`
or
`http://my.url.com/sim.html`

instead?  (i.e. omitting the key and provide a default value of [] in the QSM schema?)

**Comment by samreid** [comment]
Alternatively, we could add (optional?) array boundaries, like:

`http://my.url.com/sim.html?exploreNumbers=[]&hello`
`http://my.url.com/sim.html?exploreNumbers=[0,2,81]&hello`

**Comment by jonathanolson** [comment]
> Can I access the new version when I am on campus this morning?

I'll have a URL accessible very soon.

**Comment by jonathanolson** [comment]
> (i.e. omitting the key and provide a default value of [] in the QSM schema?)

The default needs to be [ 10 ].

>  they look like syntax errors
> Alternatively, we could add (optional?) array boundaries

No strong preference (lean towards suggested empty-string value instead of requiring brackets), but it would be ideal to have at least one way to input empty arrays.

**Comment by jonathanolson** [comment]
@bethstade, try http://phettest.colorado.edu/make-a-ten/build/make-a-ten_en.html.

**Comment by bethstade** [comment]
The cue look good.  And the logic you implemented makes sense and seems consistent.  I really like how persistent the cues are.

**Comment by samreid** [comment]
I created a QSM issue for investigation.  How soon do you need this?

**Comment by jonathanolson** [comment]
> I created a QSM issue for investigation. How soon do you need this?

?exploreNumbers=0 is a current workaround, I don't think it's at all high priority. It's just something I thought would (and should) work.

**Comment by amanda-phet** [comment]
@jonathanolson 
1. The circular cue is perfect. 
2. That sounds correct.
3. That works for me.
4. Yes, you are correct. I should have been more specific. 

This looks great to me!

**Comment by amanda-phet** [comment]
@jonathanolson When Kathy observed a teacher using this sim, she thought the circular arrow cue was implying that something "fancy" would happen, or that she had to spin something around. We agreed that a straight, 45˚ arrow pointing NE would be clearer. Can you possibly implement this change today/tomorrow so I can try to schedule interviews for 11/23?

**Comment by jonathanolson** [comment]
Updated in master, dev deploy available (for interviews) at http://www.colorado.edu/physics/phet/dev/html/make-a-ten/1.0.0-dev.11/make-a-ten_en.html.

**Comment by amanda-phet** [comment]
Decision in 12/1/16 meeting: adjust arrow cues once again. There will only be ONE cue (pull apart). Behind it should be a semi-transparent rectangle covering the number up to the top of the paper. This cue will still be persistent, so if it jumps from a 10 to 100 the size of the rectangle will need to be adjusted accordingly. 

<img width="312" alt="screen shot 2016-12-05 at 12 34 58 pm" src="https://cloud.githubusercontent.com/assets/7852916/20899389/7cf1b902-bae7-11e6-94b4-1ef8a0ff1858.png">

<img width="275" alt="screen shot 2016-12-05 at 12 40 09 pm" src="https://cloud.githubusercontent.com/assets/7852916/20899517/fd1d754e-bae7-11e6-9778-d7960c6f0876.png">

**Comment by jonathanolson** [comment]
Added to master (the highlighted area covers the exact bounds used by the mouse, and it's slightly larger).

Let me know if that looks good, or needs any other changes.

**Comment by amanda-phet** [comment]
I really like that the highlighted area is the mouse region. I know that some in the design meeting didn't like that the rectangle went through the middle of the digits, but I think the cue has more impact this way. I like the way it switches between numbers, and especially like that I see it when I build a 2. 

Unless anyone has objections to this rectangle size, I'd like to use this in the next round of interviews.

**Comment by ariel-phet** [comment]
@bethstade just as a note, if you VPN to campus you can always look on phettest

**Comment by bethstade** [comment]
Thanks for the VPN reminder -
Yes, good impact with the shading.
The single cue looks good and simple too.
It would be interesting to see how adults react to this cue too.

**Comment by amanda-phet** [comment]
@bethstade do you want to see how adults/teachers react to the cue? 

I didn't see any issues in interviews. I think students are better at "ignoring" this sort of thing, but all students figured out how to split apart numbers so I think the single cue is doing its job.

**Comment by bethstade** [comment]
If it working for the students I think we have it. Sounds like it is working the way we wanted it.  I don;t need to see how adults react.

**Comment by amanda-phet** [comment]
Thanks @bethstade !
