### ISSUE TITLE
Redefine touch areas for number pieces

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/make-a-ten#233]
Based on observations of teachers using the sim, we would like to move the touch areas back to the "original" spec. The top 2/3 of the number piece is the touch area for pulling apart a number. The bottom 1/3 of the number piece is the touch area for moving. 

![screen shot 2016-10-10 at 10 21 08 am](https://cloud.githubusercontent.com/assets/7852916/19243354/91479172-8ed4-11e6-9c32-589eb520c3bb.png)

**Comment by jonathanolson** [comment]
Applied, and ?showPointerAreas can help show where the exact boundaries are.

**Comment by bethstade** [comment]
This is very nice.  Now touching the middle of the number pulls part, but just below moves.  I think this will help users find the actions much quicker.

**Comment by amanda-phet** [comment]
The touch areas look good. Closing this issue, but if interviews show us that the touch areas need to be changed I will re-open this issue.
