### ISSUE TITLE
Change color of level selection buttons

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/make-a-ten#234]
![screen shot 2016-10-10 at 10 46 29 am](https://cloud.githubusercontent.com/assets/7852916/19243881/d5f09c4a-8ed6-11e6-8e6e-cdf9e38adff1.png)

We would like to update the color scheme for the level selection buttons to the following colors:
![screen shot 2016-10-10 at 10 47 04 am](https://cloud.githubusercontent.com/assets/7852916/19243892/f25ea3e0-8ed6-11e6-86ae-2f6023853ddf.png)

And just to be sure we're using the right shade of green for the background, it should be #E8FFB0.

**Comment by jonathanolson** [comment]
Looks like the background color is off, will fix.

For reference:

- Current background color: RGB 217, 252, 146
- Requested background color: RGB 232, 255, 176

**Comment by jonathanolson** [comment]
Color changes made. The buttons have a different shading appearance than in the above mock-up (the 3D effect is more isolated to the edges), let me know if that's a problem.

**Comment by amanda-phet** [comment]
/make-a-ten/make-a-ten_en.html is not found. 
/make-a-ten/making-tens_en.html works but does not seem to be the most recent version. 

Does something here need to be changed so that I can view latest build versions of the sim? Otherwise I'll need dev versions published.

**Comment by jonathanolson** [comment]
Checking, I presume you are using phettest.colorado.edu?

**Comment by amanda-phet** [comment]
Correct.

**Comment by jonathanolson** [comment]
I kicked off a "Pull All", hopefully that will fix it, but I'll let you know.

**Comment by jonathanolson** [comment]
Seems to be working for me now, can you check?

**Comment by amanda-phet** [comment]
It's working now, thanks. 

Also the colors look great!
