### ISSUE TITLE
Add a status bar on game screens

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/make-a-ten#235]
We would like a status bar on the game screens that includes a back button (that returns the user to the level selection screen), the level number, the level description, and the total number of correct problems for that level. 

The color of the status bar should coordinate with the level selection button. 

![screen shot 2016-10-10 at 10 49 39 am](https://cloud.githubusercontent.com/assets/7852916/19243955/4845b226-8ed7-11e6-80cc-77af6f23b4aa.png)

![screen shot 2016-10-10 at 10 50 02 am](https://cloud.githubusercontent.com/assets/7852916/19243969/56971662-8ed7-11e6-8b33-ab91dc65a917.png)
![screen shot 2016-10-10 at 10 50 09 am](https://cloud.githubusercontent.com/assets/7852916/19243970/5698525c-8ed7-11e6-8e3c-030410626938.png)

**Comment by jonathanolson** [comment]
Implemented initial version, but initially sharing the score display with the level-start buttons (the star with number of challenges completed for the level).

1. Do we want to have a slightly different display of the score on the buttons compared to the status bar? It flips the side the number is on, and the mock-up shows a non-empty star for 0.
2. Do we want to darken the status bar background color slightly, so the white text shows up a bit better?

Additionally, let me know about the layout of text in the bar (what should be changed, and how alignment should work). It can expand/shrink based on the browser aspect ratio, and I made my best guess about desired behavior based on the mock-up.

**Comment by amanda-phet** [comment]
1. What you have implemented (with a gray/empty star) looks good to me. 

2. I'd like to see what the team thinks. The colors are pretty bright and I wouldn't mind darkening them a bit, but we did pick colors that went well together and also passed AA accessibility standards for readability. 

As for the text layout, can you make the level description left-aligned rather than center-aligned? The rest of  it looks good to me (the shrinking, size, etc.)

**Comment by jonathanolson** [comment]
> I'd like to see what the team thinks. The colors are pretty bright and I wouldn't mind darkening them a bit, but we did pick colors that went well together and also passed AA accessibility standards for readability.

Sure, only the magenta was even possibly an issue. It's definitely readable to me, so I'm not worried if it also passes standards.

> As for the text layout, can you make the level description left-aligned rather than center-aligned? The rest of it looks good to me (the shrinking, size, etc.)

Will do.

**Comment by jonathanolson** [comment]
Left-aligned the description with the same padding that the level number text gets, let me know if it looks good.

**Comment by amanda-phet** [comment]
The alignment looks perfect to me. 

To make the text more readable and have a better contrast ratio, can you please do two things:
1. Make the text black (#000000)
2. Change the purple color (for the level selection buttons and the status bar) to #9778CC

I checked with the [color contrast checker] (http://webaim.org/resources/contrastchecker/) and for all three colors we are AAA for large text and AA for small text, so this should fix the problem. Thank you!

**Comment by jonathanolson** [comment]
Done, let me know how it looks.

**Comment by amanda-phet** [comment]
Looks good. Thank you! Closing.
