### ISSUE TITLE
Increase text size on "next" button

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/make-a-ten#236]
Currently: 
![screen shot 2016-10-10 at 10 51 53 am](https://cloud.githubusercontent.com/assets/7852916/19244014/96fd1986-8ed7-11e6-9f21-e12c487d1546.png)

Should be closer to: 
![screen shot 2016-10-10 at 10 52 48 am](https://cloud.githubusercontent.com/assets/7852916/19244040/b7217f18-8ed7-11e6-9f4f-a1eedf9a6f2f.png)

**Comment by jonathanolson** [comment]
Changes applied, let me know if it looks OK.

**Comment by amanda-phet** [comment]
Looks good.
