### ISSUE TITLE
Make keypad larger

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/make-a-ten#238]
The size of the keypad buttons seems small. Can we make sure we are using the common component keypad that is used in Area Builder? The Area Builder one seems to have larger buttons. For this sim, since users will likely be younger and less precise, we want the keypad buttons to be slightly larger. 

![screen shot 2016-10-10 at 10 56 11 am](https://cloud.githubusercontent.com/assets/7852916/19244206/6986a14c-8ed8-11e6-843e-ca76fcf12533.png)

![screen shot 2016-10-10 at 10 56 02 am](https://cloud.githubusercontent.com/assets/7852916/19244210/6ccabaa0-8ed8-11e6-9984-b3f81507b5d8.png)

While we're at it, can we also reduce the size of the gray panel behind the keypad? It doesn't need nearly that much padding.

**Comment by jonathanolson** [comment]
Changed, can you see if that looks acceptable? It is also now using the same control (code refactored to be shared in another issue).

**Comment by amanda-phet** [comment]
Looks great to me!
