### ISSUE TITLE
Number images have varying dimensions

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/make-a-ten#241]
They typically vary by a pixel, noted:

``` js
    // TODO: These don't seem consistent. Here are the current sizes:
    // 1-digit numbers have image dimensions of 67x128
    // 2-digit numbers have image dimensions of (155,156)x(140,141)
    // 3-digit numbers have image dimensions of 215x177
    // 4-digit numbers have image dimensions of (271,272)x189
    PAPER_NUMBER_DIMENSIONS: {
      1: new Dimension2( 67, 128 ), // key is digitLength
      2: new Dimension2( 156, 141 ),
      3: new Dimension2( 215, 177 ),
      4: new Dimension2( 272, 189 )
    },
```

**Comment by jonathanolson** [comment]
@amanda-phet, is the original artwork in a place where I could potentially extract identical-sized images without the pixel variations?

**Comment by amanda-phet** [comment]
That's strange! I will add the illustrator file to the assets.

**Comment by amanda-phet** [comment]
Can you please create an "assets" folder in this repo? I'm not sure I can/know how.

**Comment by jonathanolson** [comment]
It's a quirk of git that it doesn't store empty folders. If the upload button doesn't allow it, feel free to add them however and I can move them into place (or send an email to me with them).

**Comment by jonathanolson** [comment]
Thanks, added it in the commit above. I'll look into getting same-size images.
