### ISSUE TITLE
Consider BAM-like repulsion for numbers

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/make-a-ten#245]
With 3+ numbers, it's possible to cause overlapping numbers that may be tricky:
![screen shot 2016-10-28 at 12 41 09 pm](https://cloud.githubusercontent.com/assets/480878/19818192/f7623418-9d0b-11e6-9a99-83f77d3b6d7c.png)
(in this example, there are two numbers on the left, and one on the right).

Should I look into a Build a Molecule-like repulsion, where:
1. Any non-combined numbers always push away from each other until they are a certain distance away.
2. Numbers don't go outside of the normal draggable boundary (and would treat the explore panel like a boundary).

That means that if a number A is dropped near number B (which can't add), B won't end up on/under another number C after being pushed away, but instead would push away C.

**Comment by bethstade** [comment]
I am not sure we want to address this.  We also see this issue with single digits and double digits - you can put a 3 onto of the one digit of the number 10 and it looks like a 30.  I believe we decided NOT to address this unless it was an issue in interviews.  It is something teachers have pointed out, but we can also see the advantages to less jumpy behavior and discussion about how numbers look.

**Comment by amanda-phet** [comment]
Let's consider this after interviews.

**Comment by amanda-phet** [comment]
I think I understand this better now. This is an odd scenario and seems like it could be confusing to a user if they encounter it. 

With a BAM-like repulsion, I could also see a domino effect happening if the play area is covered with numbers. What would happen if there is no room for numbers to repel? Would they eventually combine? Or overlap as they do now?

**Comment by jonathanolson** [comment]
> With a BAM-like repulsion, I could also see a domino effect happening if the play area is covered with numbers. What would happen if there is no room for numbers to repel? Would they eventually combine? Or overlap as they do now?

They would presumably fill all available room on the screen as evenly as possible without combining.

Currently the only way to combine numbers is to actually "drop" one.

**Comment by amanda-phet** [comment]
I can see why this might be useful, but I worry about too much repelling. In interviews, if students tried to combine numbers that were not allowed to combine (such as 29+29) and they repelled, it forced them to think about that. If it's happening too much, that feedback might not be as meaningful.
