### ISSUE TITLE
Performance Check

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/make-a-ten#251]
I just checked on an old iPad 3 (as part of the code-review guidelines), and the performance seems fairly acceptable, with the most annoying thing being a slight delay when dragging a number out of the bottom panel on the Explore screen.

@ariel-phet, should this wait for dev/RC testing, or does the performance seem acceptable?

**Comment by ariel-phet** [comment]
Played with the sim on iPad 2 and performance seems perfectly smooth. I see no issues.

@jonathanolson good to have done a performance check now, but all seems good. QA will reveal if there if there are any subtle problems, but all looking good!
