### ISSUE TITLE
Touch areas for papers (again)

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/make-a-ten#252]
Please change the touch areas for the "pull apart" region and "move" region so that "pull apart" is the top 45% of the paper and "move" is the bottom 55% of the paper.

**Comment by jonathanolson** [comment]
Change made in master.

**Comment by amanda-phet** [comment]
I will keep this assigned until I do interviews.

**Comment by amanda-phet** [comment]
These worked very well in interviews. 

At the end of the interviews I asked students how to split apart a number vs. move it and they did not realize there were two touch areas because they had all used two fingers to literally pull apart a number. However, I did not see nearly as much frustration when trying to move numbers, and all students found a way to pull apart numbers when they wanted to (most used two fingers to literally split apart a number, and it worked well for them to continue doing that even after learning about the touch areas!).

**Comment by bethstade** [comment]
great!
