### ISSUE TITLE
Make number readouts black

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/make-a-ten#253]
On all three screens, there is a number readout that is currently a shade of blue. 

<img width="135" alt="screen shot 2016-12-05 at 12 29 48 pm" src="https://cloud.githubusercontent.com/assets/7852916/20899202/b3b19206-bae6-11e6-8857-c2d4e6924ab8.png">
<img width="231" alt="screen shot 2016-12-05 at 12 30 00 pm" src="https://cloud.githubusercontent.com/assets/7852916/20899211/bb19218a-bae6-11e6-865a-9bb488a60c5d.png">
<img width="867" alt="screen shot 2016-12-05 at 12 30 06 pm" src="https://cloud.githubusercontent.com/assets/7852916/20899217/c4453d66-bae6-11e6-8b1a-85881e7fd1dd.png">

We'd like to change the color to black. 

If we keep it black, we will also need to adjust the screen icons.

**Comment by jonathanolson** [comment]
Changed in master, let me know if I should make other changes, or wait on updated screen icon images.

**Comment by amanda-phet** [comment]
All students in the second round of interviews attended to the total when interacting on the explore screen, so I think this is working well.
