### ISSUE TITLE
Add a reward after user completes 10 challenges

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/make-a-ten#254]
Based on interviews and discussions with a collaborator, we would like to add a reward on the game screen that functions like this: After completing 10 challenges (on any level), the screen shows confetti and a dialog pops up with two options: continue playing the current level, or go back to the level selection. 

<img width="681" alt="screen shot 2016-12-05 at 12 53 23 pm" src="https://cloud.githubusercontent.com/assets/7852916/20899999/db7c9940-bae9-11e6-89d7-eaecf6c4abc0.png">

If the user clicks "keep going", it essentially dismisses the dialog. If the user clicks "new level!" they return to the level selection screen. 

The phet-girl artwork is simply the game screen artwork.

**Comment by jonathanolson** [comment]
Is this a modal pop-up (i.e. can the user click on the Next button, status bar back button, or anything behind)?

If so, do you want the usual hint that there is a modal dialog (generally a semi-transparent layer in front of everything else but behind the dialog)? It would presumably cover anything that can't be interacted with (so not covering the navigation bar below, assuming that is left as an option to switch screens).

If not, does clicking "Next" remove the dialog? Does going back to the level selection area clear it?

**Comment by jonathanolson** [comment]
Also, can you clarify:

> the screen shows confetti

Is that like the rewards in other sims? We have a dedicated RewardNode where you give it things to fall from the top of the screen.

If not, can you clarify what the appearance should be like? I can also give it a go if you want.

**Comment by amanda-phet** [comment]
>Is this a modal pop-up (i.e. can the user click on the Next button, status bar back button, or anything behind)? If so, do you want the usual hint that there is a modal dialog (generally a semi-transparent layer in front of everything else but behind the dialog)? It would presumably cover anything that can't be interacted with (so not covering the navigation bar below, assuming that is left as an option to switch screens).

I think it should be modal. Does that seem appropriate to you? I was basing it on the pop-up in Arithmetic, but that one does not have the semi-transparent layer. Let's make it modal, and add the semi-transparent layer to cue this. Clicking outside dismisses the dialog and allows the user to continue playing that level. 

>Is that like the rewards in other sims? We have a dedicated RewardNode where you give it things to fall from the top of the screen. 

Yes, I couldn't remember which sim had this, but it had things like stars and smiling faces dropping from the top of the screen. It might've been a chemistry sim, because I also remember little molecules dropping. If we need to customize what drops, let me know and I'll think of something (numbers and stars, perhaps).

**Comment by jonathanolson** [comment]
Modal with a semi-transparent background sounds great to me, and I'll experiment with the RewardNode (presumably falling paper numbers, smileys, etc.). Thanks!

**Comment by jonathanolson** [comment]
Did initial implementation, let me know about any changes (it's in master).

The stroke on the star is thicker than in the mock-up. If that's a problem, I can generalize the common code to allow different stroke thicknesses (shouldn't be hard, let me know).

**Comment by amanda-phet** [comment]
Looks great to me! 

I'd like to see what other team members think as well, since we didn't spend a lot of time on the design. @bethstade @ariel-phet

**Comment by bethstade** [comment]
omg that is so cute!!!
Great preview for raining tens.


----- Original Message -----From: Amanda McGarry <notifications@github.com>To: phetsims/make-a-ten <make-a-ten@noreply.github.com>Cc: bethstade <stadee@colorado.edu>, Mention <mention@noreply.github.com>Sent: Wed, 07 Dec 2016 20:16:26 -0000 (UTC)Subject: Re: [phetsims/make-a-ten] Add a reward after user completes 10 challenges (#254)

Looks great to me!
I'd like to see what other team members think as well, since we didn't spend a lot of time on the design. @bethstade@ariel-phet
&mdash;You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ariel-phet** [comment]
@amanda-phet will look....reminder please always assign me to issues for a response :)

**Comment by ariel-phet** [comment]
@amanda-phet looks good to me

**Comment by amanda-phet** [comment]
This worked really well in interviews. One student intentionally chose to keep going because she was feeling successful on that level, and another preferred to go back and master each level. I think this helped both students make a choice that worked for them.
