### ISSUE TITLE
Add "swipe" to game screen

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/make-a-ten#255]
When the user clicks on a level, I think it would be nice if they see the first challenge enter from the right side (so the screen swipes left). 
<img width="120" alt="screen shot 2016-12-05 at 12 59 17 pm" src="https://cloud.githubusercontent.com/assets/7852916/20900217/b6ae94f0-baea-11e6-8805-96b0ae2dd9e9.png">

Successive challenges would not show any swiping, however.

When they click the back arrow, the screen swipes to the right. 
<img width="142" alt="screen shot 2016-12-05 at 12 59 27 pm" src="https://cloud.githubusercontent.com/assets/7852916/20900231/be8c914a-baea-11e6-873b-e92d1e9dcbf3.png">

**Comment by jonathanolson** [comment]
Should the top status bar also animate into place, or should it appear at the start or end of animation?

Additionally, I'll plan to make it so things animating on the "pick a level" screen can't be clicked while animating; allowing clicking things while animating would make the logic quite complicated.

**Comment by amanda-phet** [comment]
>Should the top status bar also animate into place, or should it appear at the start or end of animation? 

What do you think makes more sense or looks better? I'm having a hard time picturing it appearing after the animation. I was picturing the entire window that you see on a game level as the "screen" that is swiping.

**Comment by jonathanolson** [comment]
I'll probably have the status bar animate by default, and if that's weird we can try it without movement.

**Comment by amanda-phet** [comment]
That sounds good to me, and what I would expect. 

Thanks!

**Comment by jonathanolson** [comment]
Added in master, let me know how it looks.

**Comment by amanda-phet** [comment]
Perfect. That's exactly how I pictured it looking.

**Comment by bethstade** [comment]
yes.  looks good.


----- Original Message -----From: Amanda McGarry <notifications@github.com>To: phetsims/make-a-ten <make-a-ten@noreply.github.com>Sent: Wed, 07 Dec 2016 18:37:24 -0000 (UTC)Subject: Re: [phetsims/make-a-ten] Add "swipe" to game screen (#255)

Perfect. That's exactly how I pictured it looking.
&mdash;You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
