### ISSUE TITLE
Adjust threshold for number going off screen

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/make-a-ten#257]
In interviews, students would "lose" a 1 off to the sides of the screen, and in particular on an iPad this was frustrating. When it went to the left side, they would try to pull it back and ended up swiping "back" in the browser. 

I recommend that we change the threshold so that paper numbers can not go beyond the right and left edges of the viewport *at all*. We currently have it set so that 50% of the number can go off, but that even leaves a mystery as to what number could even be hiding there, so I think that the full paper needs to stay visible in the viewport. 

If we do this for the left and right, we might as well do it for the top boundary as well. @bethstade please feel free to jump in if you feel strongly about this either way. If you still want to allow the numbers to hide a little bit, I would suggest a smaller percentage of the paper be allowed beyond the boundary.

**Comment by bethstade** [comment]
I do like "hiding" the numbers off-screen, but I can see the problem with the iPad, so your solution seems correct.

**Comment by amanda-phet** [comment]
Thanks for your input! Let's move forward with this change, then.

**Comment by jonathanolson** [comment]
Changes made in master, let me know how it looks (or if a dev version is needed).

**Comment by amanda-phet** [comment]
Looks good to me, thank you.
