### ISSUE TITLE
Change screen icons to reflect black text

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/make-a-ten#258]
https://github.com/phetsims/make-a-ten/issues/253

**Comment by jonathanolson** [comment]
Exporting them would be great, I still have a lot of uncertainty about the exporting process. They're checked in as images:

- make-a-ten/images/adding-home-screen.png
- make-a-ten/images/adding-nav-bar.png
- make-a-ten/images/explore-home-screen.png

**Comment by amanda-phet** [comment]
Thanks, I see those now. I replaced those image files in github.

**Comment by amanda-phet** [comment]
@jonathanolson is there anything else I need to do?

**Comment by jonathanolson** [comment]
Nope, thanks!
