### ISSUE TITLE
Adjust region for overlapping numbers to combine

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/make-a-ten#260]
In an impromptu meeting we discussed a new boundary for when overlapping numbers should combine. The rule should be: if the center of the top number is within an ellipse around the bottom number, they will combine. (The actual ellipse may need some tweaking that @jonathanolson can do in the code.) 

![screen shot 2017-01-05 at 3 00 55 pm](https://cloud.githubusercontent.com/assets/7852916/21699189/ccf45c24-d357-11e6-9feb-6224cbaa6232.png)

![screen shot 2017-01-05 at 3 00 59 pm](https://cloud.githubusercontent.com/assets/7852916/21699193/d26e9714-d357-11e6-9d51-e8492d0578e1.png)

@kathy-phet please comment if I'm missing something!

**Comment by kathy-phet** [comment]
Agreed. Thanks.

**Comment by kathy-phet** [comment]
@jonathanolson - Can you also let me know when a new dev when this is up on this? I want to share it with a teacher who will be taking it for a test drive in her class.

**Comment by jonathanolson** [comment]
Applied in master (dev version http://www.colorado.edu/physics/phet/dev/html/make-a-ten/1.0.0-dev.14/make-a-ten_en.html, let me know if another is needed if things are tweaked).

An ellipse height of ~70% of the paper number seemed to work well (technically 1/sqrt(2)), but this can be easily adjusted.

**Comment by kathy-phet** [comment]
@jonathanolson - Thanks! I like the way this behaves in terms of combining distance. I also took some time to digest the algorithm for which number jumps and which stays put, and I have a suggestion for that. 

Right now it seems like it behaves according to the following rules: 
- if one number is numerically bigger than the other number, the bigger one stays put and the smaller one jumps to its position. 
- if the numbers are equal, the one that is being moved by the mouse stays where it was put and the other one jumps to meet it. 

There are some cases where this seems fine ... e.g. placing a smaller number on a larger number, this works as I would expect, but there are times when this feels off. I would suggest a slightly different algorithm (depending on how much effort it is to adjust this behavior): 
- if the place value of the numbers that are overlapped is the same (e.g. both 3 places), then the one that your mouse is on is the one that jumps (e.g. it behaves as if it is adding itself to the stationary number). 
- if the two numbers have different place value lengths, the larger one stays put and the smaller one jumps to add itself to that bigger number regardless of which one is being held by the mouse (this is the same as the current behavior for this situation). 

I think this would be a bit easier to follow in terms of adding things together ... particularly numbers with the same placevalue length.

**Comment by amanda-phet** [comment]
Now that we have a much larger region that allows two number to combine, I agree that some tweaking is a good idea. It was more subtle before because the numbers were overlapping so much, but now it is more obvious when a number jumps. 

In your first suggestion, I am interpreting what you are saying to mean, the one that is *on top* (which is also the one your cursor is on), is the one that jumps. That makes sense to me that it should meet the stationary number. 

I'm not sure about the second suggestion. I wonder if it would be better to stick with one rule, that the number on top always jumps to the stationary number.

**Comment by amanda-phet** [comment]
Discussed with @kathy-phet and there is a good reason for the two suggestions. Let's move forward with both: 

* if the place value of the numbers that are overlapped is the same (e.g. both 3 places), then the one that your mouse is on is the one that jumps (e.g. it behaves as if it is adding itself to the stationary number).
* if the two numbers have different place value lengths, the larger one stays put and the smaller one jumps to add itself to that bigger number regardless of which one is being held by the mouse (this is the same as the current behavior for this situation).

**Comment by kathy-phet** [comment]
@jonathanolson - Please let us know if this is a difficult code change, or not. Thanks.

**Comment by jonathanolson** [comment]
It shouldn't be difficult, I'll implement the changes.

**Comment by jonathanolson** [comment]
Done (sorry about the delay).

Let me know if that behaves as expected, and whether I should create a dev version for testing.

**Comment by kathy-phet** [comment]
should i try it in phettest then?

**Comment by jonathanolson** [comment]
That would work. I'll publish a dev version to make it easy though (in case it is also used  for other testing).

**Comment by kathy-phet** [comment]
I ran it on phetest -- works great! Thanks! Yes, I would say make a new dev link and lets ask Steele to run it through all the testing.

**Comment by kathy-phet** [comment]
Can you update the testing issue, with the new dev link then too?

**Comment by jonathanolson** [comment]
Will do (http://www.colorado.edu/physics/phet/dev/html/make-a-ten/1.0.0-dev.15/make-a-ten_en.html is the new link).

**Comment by jonathanolson** [comment]
Updated the testing issue.

**Comment by kathy-phet** [comment]
Thanks!

**Comment by amanda-phet** [comment]
Looking good to me.
