### ISSUE TITLE
Numbers can cross bounds when combined at the screen's edge

### ISSUE THREAD

**Issue by phet-steele** [phetsims/make-a-ten#261]
@jonathanolson this is a super picky problem. When single digits are combined into a double digit number, or double into triple, etc..., this new number grows towards the left. This is generally not an issue unless numbers are formed along the left side of the screen. The new number gets "pushed" out of the screen bounds. Any interaction with the number does fix the issue (the number sort of jumps back into bounds). I bring this up because it looks slightly weird in the game screen:

1. Put a 1 along the left of the screen in any game level (except level 1).
2. Drag a 9 to it to make a ten. Part of the 10 is now off screen.
3. Don't move the number, but press the back arrow to return to the level selection screen.

The left side of the number now peeks through. You cannot pull the number further into the level selection screen; the number is still confined to the bounds of its level:

![mat01](https://cloud.githubusercontent.com/assets/5863899/21860433/c9626a34-d7ed-11e6-950d-a6110d6aefca.gif)

Seen on macOS 10.12.2 Chrome. For phetsims/tasks/issues/762.

URL: http://www.colorado.edu/physics/phet/dev/html/make-a-ten/1.0.0-dev.15/make-a-ten_en.html
Version: 1.0.0-dev.15 2017-01-10 07:02:01 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
Language: en-US
Window: 1920x1001
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"master"},"axon":{"sha":"ec87493f","branch":"master"},"babel":{"sha":"fd922617","branch":"master"},"brand":{"sha":"0be722ee","branch":"master"},"chipper":{"sha":"ae15c093","branch":"master"},"dot":{"sha":"2b15e064","branch":"master"},"joist":{"sha":"6b7e99df","branch":"master"},"kite":{"sha":"197fef79","branch":"master"},"make-a-ten":{"sha":"24aa1f79","branch":"master"},"phet-core":{"sha":"84747dff","branch":"master"},"phetcommon":{"sha":"1cb33196","branch":"master"},"query-string-machine":{"sha":"d8a4ff18","branch":"master"},"scenery":{"sha":"9d165389","branch":"master"},"scenery-phet":{"sha":"e8dd9772","branch":"master"},"sherpa":{"sha":"785a536c","branch":"master"},"sun":{"sha":"26fa8dc3","branch":"master"},"tandem":{"sha":"5b598f04","branch":"master"},"twixt":{"sha":"cbe4c1aa","branch":"master"},"vegas":{"sha":"f67a6f3e","branch":"master"},"vibe":{"sha":"22223265","branch":"master"}}

**Comment by jonathanolson** [comment]
Pushed a fix, can you test master to confirm?

**Comment by phet-steele** [comment]
:+1:, thanks.
