### ISSUE TITLE
Hint on the first screen can be absent momentarily

### ISSUE THREAD

**Issue by phet-steele** [phetsims/make-a-ten#262]
The split hint is lost if a user places a number with the hint into the tool box. I don't know how imperative it is to have the hint persist until a user actually splits a number (I'd imagine it is important), but on the plus side the hint returns upon the next interaction with a number.

![mat02](https://cloud.githubusercontent.com/assets/5863899/21862780/e4d73b6e-d7f7-11e6-8503-b292475b50df.gif)

Seen on macOS 10.12.2 Chrome. For phetsims/tasks#762.

URL: http://www.colorado.edu/physics/phet/dev/html/make-a-ten/1.0.0-dev.15/make-a-ten_en.html
Version: 1.0.0-dev.15 2017-01-10 07:02:01 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
Language: en-US
Window: 1920x1001
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"master"},"axon":{"sha":"ec87493f","branch":"master"},"babel":{"sha":"fd922617","branch":"master"},"brand":{"sha":"0be722ee","branch":"master"},"chipper":{"sha":"ae15c093","branch":"master"},"dot":{"sha":"2b15e064","branch":"master"},"joist":{"sha":"6b7e99df","branch":"master"},"kite":{"sha":"197fef79","branch":"master"},"make-a-ten":{"sha":"24aa1f79","branch":"master"},"phet-core":{"sha":"84747dff","branch":"master"},"phetcommon":{"sha":"1cb33196","branch":"master"},"query-string-machine":{"sha":"d8a4ff18","branch":"master"},"scenery":{"sha":"9d165389","branch":"master"},"scenery-phet":{"sha":"e8dd9772","branch":"master"},"sherpa":{"sha":"785a536c","branch":"master"},"sun":{"sha":"26fa8dc3","branch":"master"},"tandem":{"sha":"5b598f04","branch":"master"},"twixt":{"sha":"cbe4c1aa","branch":"master"},"vegas":{"sha":"f67a6f3e","branch":"master"},"vibe":{"sha":"22223265","branch":"master"}}

**Comment by jonathanolson** [comment]
@amanda-phet, when the cue is removed because the number went away, should it randomly pick another number in play to be on, or should we keep the current behavior?

**Comment by amanda-phet** [comment]
Hm, I'd say have the hint jump to the 10 sitting out, but if there are multiple numbers in the play area then there wouldn't be an obvious number for it to jump to. The current behavior seems ok to me...

**Comment by bethstade** [comment]
I agree with Amanda.

----- Original Message -----From: Amanda McGarry <notifications@github.com>To: phetsims/make-a-ten <make-a-ten@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Sent: Wed, 11 Jan 2017 19:24:01 -0000 (UTC)Subject: Re: [phetsims/make-a-ten] Hint on the first screen can be absent momentarily (#262)

Hm, I'd say have the hint jump to the 10 sitting out, but if there are multiple numbers in the play area then there wouldn't be an obvious number for it to jump to. The current behavior seems ok to me...
&mdash;You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jonathanolson** [comment]
So if there is an unambiguous number for it to jump to, it should? Otherwise have no cue for a bit?

**Comment by amanda-phet** [comment]
@jonathanolson I think this is fine. As @phet-steele pointed out, it is only absent momentarily.

**Comment by amanda-phet** [comment]
I seem to be replying at the same time as you @jonathanolson sorry. 

Let's keep the current behavior.

**Comment by jonathanolson** [comment]
Closing, thanks for mentioning it @phet-steele.
