### ISSUE TITLE
Reward modal doesn't scale its strings

### ISSUE THREAD

**Issue by phet-steele** [phetsims/make-a-ten#264]
@jonathanolson, the reward modal does not have a max width on its bounds (probably). It gets wider when strings get longer. Not a big deal since `?stingTest=double` passes:

double:
<img width="1920" alt="screen shot 2017-01-11 at 2 28 28 pm" src="https://cloud.githubusercontent.com/assets/5863899/21901116/b63de89a-d8b3-11e6-949f-ad7c606af874.png">

xss (really long):
<img width="1920" alt="screen shot 2017-01-12 at 10 41 03 am" src="https://cloud.githubusercontent.com/assets/5863899/21901108/b15d4794-d8b3-11e6-9f3f-8f82200805d2.png">

Seen on macOS 10.12.2 Chrome, somewhat worse but still passable on mobile Safari. For phetsims/tasks/issues/762.

**Comment by jonathanolson** [comment]
Fixed in master, can you check?

**Comment by phet-steele** [comment]
🐩
