### ISSUE TITLE
Should the keypad be a modal?

### ISSUE THREAD

**Issue by phet-steele** [phetsims/make-a-ten#265]
@jonathanolson @amanda-phet as it stands, when I click on the edit buttons to bring up the keypad, the only way "out" is to either submit a number or press Reset All. Clicking elsewhere in the sim, or clicking the edit button again, does not dismiss the keypad. This is unfortunate because both of those options, submit and/or Reset All, will wipe any progress I've made on this screen. This is especially punishing if I hit the edit button on accident. Maybe we bring up the keypad as a modal, and put a barrier rectangle behind it so it's dismissible? I'm think something along the lines of what [Unit Rates](http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.39/unit-rates_en.html) is doing.

For phetsims/tasks/issues/767.

**Comment by amanda-phet** [comment]
If you hit the edit button on accident, doesn't the current number show up in the readout? So, you could in theory click "submit" and nothing will have changed, unless you pressed a number or pressed the backspace. 

Perhaps we could add an 'x' to click on to close the dialog? I hesitate to dim the background in this sim because we want to clearly be able to see the problem and number pieces.

**Comment by phet-steele** [comment]
> If you hit the edit button on accident, doesn't the current number show up in the readout? So, you could in theory click "submit" and nothing will have changed, unless you pressed a number or pressed the backspace.

Clicking submit will reset the numbers back to their default state. If there was any splitting/combining prior to clicking submit, that would be lost.

![mat03](https://cloud.githubusercontent.com/assets/5863899/22520351/33b409b8-e871-11e6-94b6-d29e2c5e12f1.gif)

**Comment by phet-steele** [comment]
> I hesitate to dim the background in this sim because we want to clearly be able to see the problem and number pieces.

@amanda-phet I don't see why this is a problem. The numbers nor the papers dynamically update while you are inputting a number. To me this means there is nothing to "see" as the sim is remaining static. The focus becomes the keypad and not the rest of the sim. Once you submit, the sim would no longer be dimmed and attention would be brought back to the equation and number pieces.

**Comment by phet-steele** [comment]
I found two notes in the design doc: 

> The keyboard will disappear if you click outside of it, and the number will stay what it was. 

> If a user clicks/taps outside of the keypad, it will disappear and nothing will change.

Granted I don't know if these decisions were ever reverted, but I couldn't find evidence to say otherwise. Maybe the middle ground is to NOT have the sim be grayed, but still allow clicks outside of the keypad that close it? I'm not huge fan of this idea since it would break consistency with Unit Rates.

**Comment by amanda-phet** [comment]
I thought I remembered that being the specification! Thanks for looking, @phet-steele . I looked closer at Unit Rates and the dimming is not too bad, so I'd say we should go that route. 

@jonathanolson can you comment on the current implementation of the keypad? Is it a special non-modal dialog?

**Comment by phet-steele** [comment]
During a quick Skype call with @amanda-phet, we remembered that there was a decision that number pieces should still be movable when the keypad is enabled (this is the current behaviour). This would no longer be the case if we used a barrier rectangle. In order to preserve the current behaviour while also making the keypad more easily dismissible, my suggestion was:

- The sim will not gray out when the keypad is enabled
- Interactions (click/drag/tear/combine) on a number piece will not dismiss the keypad
- Clicks anywhere in empty play space will dismiss the keypad

@jonathanolson @amanda-phet how does that sound? This is still open for suggestion.

**Comment by jonathanolson** [comment]
@phet-steele, that sounds fine to me. @amanda-phet thoughts?

**Comment by amanda-phet** [comment]
>
    The sim will not gray out when the keypad is enabled
    Interactions (click/drag/tear/combine) on a number piece will not dismiss the keypad
    Clicks anywhere in empty play space will dismiss the keypad

This sounds find, but I'll discuss with @jbphet if this is compatible with the new keypad.

**Comment by jbphet** [comment]
There shouldn't be any issues with making the new keypad model - it can be done the same way it was in Unit Rates with the older keypad.

**Comment by amanda-phet** [comment]
@jbphet it's not quite a modal keypad.. it's sort of a hybrid... users can interact with the sim by dragging number papers but a click in empty space will dismiss the keypad. I don't think this is the best approach right now given our discussions about dialogs. If the new dialog is going to have an "x" to close it, that might be a better approach to take in this sim. Similar to what was done in LSR: 

![screen shot 2017-02-03 at 9 31 27 am](https://cloud.githubusercontent.com/assets/7852916/22599327/bd8b317e-e9f3-11e6-8ff6-7e17bd1099a4.png)

Let me give it a little more thought (and maybe discuss more with @phet-steele ). We should either make it truly modal, or give it a close option.

**Comment by amanda-phet** [comment]
Final decision: let's make the keypad modal with a slightly dimmed background so that a user can dismiss the keypad. I can't recall a compelling reason to keep the number pieces of paper interactive while the keypad is up, but if there is one, then when we have the new common dialog with a close button we can revisit this issue.

**Comment by jonathanolson** [comment]
Does the dimmed background also go in front of the navbar, or does it not (so the user can switch screens while it is up)?

**Comment by ariel-phet** [comment]
@jonathanolson I think we always want to leave the navbar able to be interacted with, that would be breaking major convention with our sims otherwise

**Comment by amanda-phet** [comment]
The dimmed background should not go in front of the navbar. I assumed there was a default behavior for a modal dialog so I apologize for not specifying.

**Comment by jonathanolson** [comment]
> @jonathanolson I think we always want to leave the navbar able to be interacted with, that would be breaking major convention with our sims otherwise

> The dimmed background should not go in front of the navbar.

Totally agree, that's why I asked. Our 'Dialog' type, when modal, is always in front of the navbar.

I looked into this modal dialog behavior, when done in sims, it is custom (not using Dialog) and somewhat duplicated (different colors, opacities, some trigger close on 'mouse/touch down', others on 'mouse/touch up'). Having different "glass pane" locations (some for thinks like the About/Options dialogs which block the navbar, others for screen-specific things like this) should probably be included in Dialog work (if it isn't already).

This should be implemented, can you try it out?

**Comment by amanda-phet** [comment]
Seems to be working great! 

If it's possible to have a "glass pane" in this sim, I would put one over the box that displays the number being edited. If it's not possible, let's add that to the general dialog discussion. 

Can you let me know if the glass window is a possibility?

**Comment by jonathanolson** [comment]
> If it's possible to have a "glass pane" in this sim

I was referring to a technical term, which implies a fully-transparent layer above everything else (http://docs.oracle.com/javase/tutorial/uiswing/components/rootpane.html), such that we'd have the following (in order from back to front):

1. Active screen's content (e.g. paper numbers)
2. Transparent layer (glass pane) for the screen itself, where dialogs are placed that do NOT block the navigation bar.
3. Navigation bar
4. Transparent layer (glass pane) for things that stay the same regardless of what screen is active (e.g. the About dialog), that SHOULD block the navigation bar.

Currently, (4) is supported by common (Joist) code for Dialog, but (2) is not to my knowledge.

Are you referring to having the "edited" rounded rectangle (white background, dashed stroke) with its number be in front of the "dimmed" rest of the screen's content?

**Comment by amanda-phet** [comment]
Ah, thank you for clarifying! I didn't realize it was a technical term since it was in quotes :) Yes I was thinking it meant a a cutout in the dimmed layer. 

I think the current implementation is working well so let's go ahead and close this issue.
