### ISSUE TITLE
Edit button alignment on Adding screen

### ISSUE THREAD

**Issue by phet-steele** [phetsims/make-a-ten#268]
The alignment of edit buttons in the adding screen equation looks off. My reference is both the design doc:
<img width="585" alt="screen shot 2017-02-01 at 12 15 34 pm" src="https://cloud.githubusercontent.com/assets/5863899/22522384/a2bf2c32-e878-11e6-8e05-d8198fbdc1aa.png">
and the navbar icon:
<img width="409" alt="screen shot 2017-02-01 at 12 19 19 pm" src="https://cloud.githubusercontent.com/assets/5863899/22522400/b12580a0-e878-11e6-9c75-5cf76d5c63b1.png">

Both of those look great, but are much different than what I'm seeing in the sim:

<img width="645" alt="screen shot 2017-02-01 at 12 21 37 pm" src="https://cloud.githubusercontent.com/assets/5863899/22522502/0131cc7a-e879-11e6-89b3-0eca9946788b.png">

It looks like the edit buttons should be shifted to the right so that the addition sign is directly between them. This would also put the buttons over the edge of their respective dashed box. The left button would be right aligned with it dashed box; the right button would be left aligned with its dashed box.

Seen on macOS 10.12.3 Chrome. For phetsims/tasks#767
URL: http://www.colorado.edu/physics/phet/dev/html/make-a-ten/1.0.0-rc.1/make-a-ten_en.html
Version: 1.0.0-rc.1 2017-01-25 19:57:06 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36
Language: en-US
Window: 1920x1001
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"HEAD"},"axon":{"sha":"1cf10281","branch":"HEAD"},"babel":{"sha":"d5fd82f2","branch":"master"},"brand":{"sha":"0be722ee","branch":"HEAD"},"chipper":{"sha":"f4cd39bf","branch":"HEAD"},"dot":{"sha":"75380061","branch":"HEAD"},"joist":{"sha":"d0bca742","branch":"HEAD"},"kite":{"sha":"6059ebb0","branch":"HEAD"},"make-a-ten":{"sha":"5f742dd4","branch":"HEAD"},"phet-core":{"sha":"84747dff","branch":"HEAD"},"phetcommon":{"sha":"1cb33196","branch":"HEAD"},"query-string-machine":{"sha":"d8a4ff18","branch":"HEAD"},"scenery":{"sha":"fbf816a5","branch":"HEAD"},"scenery-phet":{"sha":"b04d8086","branch":"HEAD"},"sherpa":{"sha":"785a536c","branch":"HEAD"},"sun":{"sha":"c98a7f0b","branch":"HEAD"},"tandem":{"sha":"d9c124e5","branch":"HEAD"},"twixt":{"sha":"cbe4c1aa","branch":"HEAD"},"vegas":{"sha":"8aa08377","branch":"HEAD"},"vibe":{"sha":"d4b79cf6","branch":"HEAD"}}

**Comment by jonathanolson** [comment]
@amanda-phet, does the described alignment (vertically with the closer edges of the numbers) sound good?

Also, should the keypad be centered vertically over the plus (as in the mock-up)?

**Comment by amanda-phet** [comment]
Just to clarify, what @phet-steele is describing is this (1): 
![screen shot 2017-02-03 at 9 43 28 am](https://cloud.githubusercontent.com/assets/7852916/22599794/431bed64-e9f5-11e6-9fcd-d629705a3faa.png)


but the navbar icon is aligned like this (2): 
![screen shot 2017-02-03 at 9 39 13 am](https://cloud.githubusercontent.com/assets/7852916/22599650/dcfe7de4-e9f4-11e6-93b0-13eef2f54e62.png)

Let's go with option (1).

**Comment by jonathanolson** [comment]
Understood.

> Also, should the keypad be centered vertically over the plus (as in the mock-up)?

Question still stands, mockup had the keypad centered with the plus.

**Comment by amanda-phet** [comment]
>Also, should the keypad be centered vertically over the plus (as in the mock-up)?

Thanks, I meant to address that as well. I think it's fine where it is because we want it more left so that it is less obtrusive in the play space.

**Comment by jonathanolson** [comment]
Implemented, let me know if anything else is needed.

**Comment by amanda-phet** [comment]
Looks great. Thanks!
