### ISSUE TITLE
Numbers can be removed after animating towards the tool box

### ISSUE THREAD

**Issue by phet-steele** [phetsims/make-a-ten#269]
@amanda-phet if you bounce two numbers that can't be added and one of the numbers winds up on top of the tool box, that number will be removed from the play area:

![mat04](https://cloud.githubusercontent.com/assets/5863899/22525739/c2f1b33c-e885-11e6-8b1a-2d838f59ea43.gif)

This interaction makes sense, but it also seems very unforgiving. Thoughts @amanda-phet? I think it would be okay to leave some numbers over the tool box. They can then just be easily dragged away, and this retains a student's hard work! This is what it would look like:

<img width="1917" alt="screen shot 2017-02-01 at 1 56 17 pm" src="https://cloud.githubusercontent.com/assets/5863899/22525868/48af5812-e886-11e6-92e6-e2735474d692.png">

For phetsims/tasks/issues/767.

**Comment by amanda-phet** [comment]
I agree that it would be nice to leave the number over the toolbox, but the repelling is tricky in a number of scenarios and I have accepted some weirdness that comes with it. In interviews, students did not find this to be an issue, so I'm inclined to leave it as-is.
