### ISSUE TITLE
Reset All button slightly intrudes into a level screen

### ISSUE THREAD

**Issue by phet-steele** [phetsims/make-a-ten#271]
See that small little area where the touch dilation for the Reset All button extends into the level screen? You better believe you can press the button 😄 
<img width="1920" alt="screen shot 2017-02-01 at 2 52 44 pm" src="https://cloud.githubusercontent.com/assets/5863899/22527965/6be21830-e88e-11e6-8498-c93de4f53582.png">

@jonathanolson maybe move the button over a few pixels, or reduce the dilation? We don't want someone accidentally pressing it!

Seen on iPad Air 2 iOS 10.2.1. For phetsims/tasks#767
URL: http://www.colorado.edu/physics/phet/dev/html/make-a-ten/1.0.0-rc.1/make-a-ten_en.html
Version: 1.0.0-rc.1 2017-01-25 19:57:06 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36
Language: en-US
Window: 1920x1001
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"HEAD"},"axon":{"sha":"1cf10281","branch":"HEAD"},"babel":{"sha":"d5fd82f2","branch":"master"},"brand":{"sha":"0be722ee","branch":"HEAD"},"chipper":{"sha":"f4cd39bf","branch":"HEAD"},"dot":{"sha":"75380061","branch":"HEAD"},"joist":{"sha":"d0bca742","branch":"HEAD"},"kite":{"sha":"6059ebb0","branch":"HEAD"},"make-a-ten":{"sha":"5f742dd4","branch":"HEAD"},"phet-core":{"sha":"84747dff","branch":"HEAD"},"phetcommon":{"sha":"1cb33196","branch":"HEAD"},"query-string-machine":{"sha":"d8a4ff18","branch":"HEAD"},"scenery":{"sha":"fbf816a5","branch":"HEAD"},"scenery-phet":{"sha":"b04d8086","branch":"HEAD"},"sherpa":{"sha":"785a536c","branch":"HEAD"},"sun":{"sha":"c98a7f0b","branch":"HEAD"},"tandem":{"sha":"d9c124e5","branch":"HEAD"},"twixt":{"sha":"cbe4c1aa","branch":"HEAD"},"vegas":{"sha":"8aa08377","branch":"HEAD"},"vibe":{"sha":"d4b79cf6","branch":"HEAD"}}

**Comment by jonathanolson** [comment]
Good find! Should be fixed in master.

**Comment by phet-steele** [comment]
This is fixed, thanks @jonathanolson. It's worth mentioning that the problem still exists at very wide aspect ratios. Seeing as most of our touch screen users will be on an iPad with a fixed aspect ratio, this is unlikely to ever happen. Closing.
