### ISSUE TITLE
[Test issue] Poor performance on Ipad when hitting scare of ten in a level

### ISSUE THREAD

**Issue by ayeemdee** [phetsims/make-a-ten#277]
1. Pick a level
2. Go till score of 10
3. Delay on Ipad when reward screen comes up

for phetsims/tasks/issues/849

Test device: Lenovo Thinkpad

Operating System: Win 10

Browser: Chrome

Screenshots:

Troubleshooting information (do not edit):
Name: ‪Make a Ten‬
URL: http://www.colorado.edu/physics/phet/dev/html/make-a-ten/1.0.3/make-a-ten_en.html
Version: 1.0.3 2017-04-16 17:34:11 UTC
Features missing: generatedcontent
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Language: en-US
Window: 1536x774
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"HEAD"},"axon":{"sha":"1cf10281","branch":"HEAD"},"babel":{"sha":"ee62d462","branch":"master"},"brand":{"sha":"555d21cb","branch":"HEAD"},"chipper":{"sha":"61bdb816","branch":"HEAD"},"dot":{"sha":"75380061","branch":"HEAD"},"joist":{"sha":"351df98f","branch":"HEAD"},"kite":{"sha":"6059ebb0","branch":"HEAD"},"make-a-ten":{"sha":"cdee3b3b","branch":"1.0"},"phet-core":{"sha":"84747dff","branch":"HEAD"},"phetcommon":{"sha":"e72ab604","branch":"HEAD"},"query-string-machine":{"sha":"d8a4ff18","branch":"HEAD"},"scenery":{"sha":"e4ea5931","branch":"HEAD"},"scenery-phet":{"sha":"b04d8086","branch":"HEAD"},"sherpa":{"sha":"785a536c","branch":"HEAD"},"sun":{"sha":"c98a7f0b","branch":"HEAD"},"tandem":{"sha":"d9c124e5","branch":"HEAD"},"twixt":{"sha":"cbe4c1aa","branch":"HEAD"},"vegas":{"sha":"8aa08377","branch":"HEAD"},"vibe":{"sha":"1f4dc25c","branch":"HEAD"}}

**Comment by phet-steele** [comment]
@ayeemdee fixed man, thanks for pointing it out. Can you verify?

**Comment by ayeemdee** [comment]
@phet-steele Thanks. Fixed closing.
