### ISSUE TITLE
migrate game components to vegas

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/make-a-ten#279]
For Equality Explorer, I've been asked to reuse this game "dialog" from Make A Ten.  It's implemented in `MAKE_A_TEN/game/view/RewardPanel`.  @jonathanolson do you mind if I generalize this and move it to vegas, or would you prefer to do so?

![screenshot_62](https://user-images.githubusercontent.com/3046552/35772361-f1bf4a9a-08f9-11e8-8d80-c673409ae418.png)

**Comment by pixelzoom** [comment]
Two strings and one image file will also need to move.  @ariel-phet How should we handle moving the string? Should I attempt to move it from make-a-ten to vegas string files (a lot of work), or should we require re-translation the next time that a new release branch is needed for Make A Ten?

**Comment by pixelzoom** [comment]
Hmmm...  Some other things that Equality Explorer needs to reuse: 

(1) Level-selection buttons that show number of stars. Make A Ten is creating its own `LevelButton`, not using vegas `LevelSelectionButton`.  

(2) Bar across the top that shows challenge, level, score, etc.  Again, Make A Ten is creating its own components (`GameStatusBar`, `ScoreNode`) instead of using vegas component `ScoreboardBar`. 

So there are multiple things that need to be ported.  This is a cost that I hadn't planned on.

Unclear whether the designs for Make A Ten and Equality Explorer really needed to deviate so much from vegas.  But now we have a bunch of new game components that are different from vegas, and someone needs to port them for reuse in Equality Explorer.   @ariel-phet FYI.

**Comment by pixelzoom** [comment]
I've also discovered that game-home-screen.png and game-reward.png are identical except for dimensions. Why?  This might complicate moving game-reward.png to vegas.

**Comment by pixelzoom** [comment]
Mentioning @amanda-phet, so that she's aware that there's going to be a significant cost for reusing things from Make A Ten in Equality Explorer.

**Comment by jonathanolson** [comment]
> @jonathanolson do you mind if I generalize this and move it to vegas, or would you prefer to do so?

I'm fine either way, let me know.

> I've also discovered that game-home-screen.png and game-reward.png are identical except for dimensions. Why? This might complicate moving game-reward.png to vegas.

Presumably we can only use the larger image, and use the mipmap plugin to prevent aliasing?

@pixelzoom, maybe it would be good to have a call sometime to discuss what should be moved over, and what things are now "common"? Area Model uses a somewhat similar pattern to Make a Ten, and I'd like to factor out any common behavior.

**Comment by pixelzoom** [comment]
@jonathanolson said:
> Area Model uses a somewhat similar pattern to Make a Ten, and I'd like to factor out any common behavior.

Hmm.... EqEx's game design is deviating from common-code (vegas) components because the game is “less formal” in many ways, operates differently than earlier games, and therefore has different UI components.  If sounds like Make A Ten and Area Model may have some of the same needs.  Or perhaps game design is evolving and we've found new/better ways of doing things.  All of that is fine from a design perspective.  But unless you want every game to be implementing its own UI components, we need to come up with some common UI/UX designs, so that we can create the associated common code. 

@ariel-phet @amanda-phet @kathy-phet  How do you want to proceed?

**Comment by ariel-phet** [comment]
@pixelzoom @jonathanolson we definitely want to have common behavior where possible.

Make-a-ten and EqEx have what I might term "infinite reward" levels. Basically a level where you can keep trying challenges and collecting stars, so they don't stop after a fixed number of challenges. It seems we should have a set of common code for this type of architecture, since it seems that style of game is becoming more common for us at the younger levels.

@amanda-phet, since you have been part of all these designs, can you please enumerate the common UI/UX components with this all in mind. It will also be fine if migrating the common solution to Make-a-ten results in some design tweaks. Having things common is becoming more and more important especially with keyboard nav and such.

**Comment by pixelzoom** [comment]
I'm going to defer all work on the EqEx "Solve It!" screen (game) until we've addressed the more general issue of what parts of the design and implementation should be reusable.

**Comment by pixelzoom** [comment]
@ariel-phet said:
> @amanda-phet, since you have been part of all these designs, can you please enumerate the common UI/UX components with this all in mind. It will also be fine if migrating the common solution to Make-a-ten results in some design tweaks. Having things common is becoming more and more important especially with keyboard nav and such.

Since the scope of this now exceeded "migrate to vegas", I've created a new issue for the design and implementation of game components.  See https://github.com/phetsims/vegas/issues/59.

**Comment by pixelzoom** [comment]
This issue is on hold pending identification of reusable design in https://github.com/phetsims/vegas/issues/59.

**Comment by amanda-phet** [comment]
I responded to https://github.com/phetsims/vegas/issues/59. I hope I was able to summarize the similarities between these three games.

**Comment by pixelzoom** [comment]
It's also worth noting that `MAKE_A_TEN/RewardPanel` is not a `Dialog`, presumably to avoid having to deal with `Dialog` and its standard `BarrierRectangle` (which would dim the background and be problematic for the reward animation).

**Comment by pixelzoom** [comment]
Do this when https://github.com/phetsims/vegas/issues/66 and https://github.com/phetsims/vegas/issues/59 are closed.

**Comment by jonathanolson** [comment]
Migrated to vegas components, closing.
