### ISSUE TITLE
Info button is not localized

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/make-a-ten#280]
While working on Equality Explorer, @amanda-phet and I discussed adding an "Info" button to the game level-selection screen, ala Make A Ten.   Screenshot below shows what it looks like for Make A Ten (upper-right corner).

Two problems:

(1) The '?' is hardcoded, not translatable. '?' is not universal. For example, the Greek equivalent looks like ";", and in Arabic it's "⸮". Reference: https://www.quora.com/Which-symbols-are-used-as-a-question-mark-in-languages-other-than-English.  Relevant code is MakeATenGameScreenView line 78:

`      content: new Text( '?', {`

(2) There is an international symbol for "Info", and a corresponding fontawesome glyph https://fontawesome.com/icons/info-circle?style=light.  Why is it not used here?

Assigning to @amanda-phet to decide whether to change to the international "info" symbol (highly recommended) or at least make the '?' translatable. 

![screenshot_520](https://user-images.githubusercontent.com/3046552/37984560-cccecb06-31b3-11e8-8046-153eeddcc947.png)

**Comment by pixelzoom** [comment]
This sim should use SCENERY_PHET/buttons/InfoButton when it has been created.  
See https://github.com/phetsims/scenery-phet/issues/363

**Comment by pixelzoom** [comment]
SCENERY_PHET/buttons/InfoButton now exists, you can use it at any time.

**Comment by jonathanolson** [comment]
Using InfoButton, seems a bit big. Is that expected?:

<img width="1147" alt="screen shot 2018-05-16 at 7 50 33 pm" src="https://user-images.githubusercontent.com/480878/40152447-77acfcd6-5942-11e8-9b58-5f52ea8a25b5.png">

**Comment by amanda-phet** [comment]
I agree it seems large in this context, and larger than what we see in Equality Explorer. 

Can you scale it down?

**Comment by jonathanolson** [comment]
Scaled down. Can you try master?

**Comment by amanda-phet** [comment]
Looks good to me.

**Comment by jonathanolson** [comment]
Ok, closing (reopen if I missed something).
