### ISSUE TITLE
Use Sun/SlidingScreen.js if possible.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/make-a-ten#282]
While reviewing https://github.com/phetsims/area-model-common/issues/99 with @samreid there was a request by @jonathanolson: 

> Please review SUN/SlidingScreen, which was generalized to handle the sorts of "sliding screen" animations without using TWIXT or anything hacky.

During review, we realized make-a-ten is also using a version of slidingScreen.js. If it is possible the SUN component should be used to reduce code duplication.

**Comment by jonathanolson** [comment]
I opened https://github.com/phetsims/make-a-ten/issues/281 earlier. Should we close one of the issues?

**Comment by Denz1994** [comment]
Closing this issue because it is a duplicate.
