### ISSUE TITLE
use VEGAS/SlidingScreen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/make-a-ten#283]
Why is make-a-ten not using `VEGAS/SlidingScreen` for transitions in the game?  It's used in area-model-common and fractions, and @jonathanolson is the author of all 3 sims.

**Comment by jonathanolson** [comment]
Because I haven't gotten to it yet, see https://github.com/phetsims/make-a-ten/issues/281. Also, TWIXT/SlidingScreen, right?

**Comment by pixelzoom** [comment]
Yes, TWIXT/SlidingScreen.

**Comment by jonathanolson** [comment]
Using TransitionNode (the improved version), closing.
