### ISSUE TITLE
For loop cannot loop

### ISSUE THREAD

**Issue by samreid** [phetsims/make-a-ten#294]
As part of https://github.com/phetsims/chipper/issues/814, ESLint detected this code in make-a-ten/js/make-a-ten/common/view/MakeATenCommonView.js

```js
    for ( var i = 0; i < droppedNodes.length; i++ ) {
      const droppedNode = droppedNodes[ i ];
      const droppedPaperNumber = droppedNode.paperNumber;
      const droppedNumberValue = droppedPaperNumber.numberValueProperty.value;

      if ( ArithmeticRules.canAddNumbers( draggedNumberValue, droppedNumberValue ) ) {
        this.model.collapseNumberModels( this.availableViewBoundsProperty.value, draggedPaperNumber, droppedPaperNumber );
        return; // A bit weird, but no need to relayer or try combining with others?
      }
      else {
        // repel numbers - show rejection
        this.model.repelAway( this.availableViewBoundsProperty.value, draggedPaperNumber, droppedPaperNumber );
        return; // A bit weird, but if repelled, no need to check for overlapping bits?
      }
    }
```

Note that the loop cannot loop since it always returns.  This seems potentially buggy, so I'll mark blocks publication.  I will also opt out of the lint rule for now so that it doesn't show as a lint error, but as part of the resolution for this issues the eslint disable directive should be removed.  Assigning to responsible dev.

**Comment by jonathanolson** [comment]
@chrisklus does the above commit look good to you? Only the first would be reachable, and it seems like we ignore "lower-down" numbers in range.

**Comment by chrisklus** [comment]
That looks great, thanks! Closing.
