### ISSUE TITLE
Plus sign overlaps numbers

### ISSUE THREAD

**Issue by samreid** [phetsims/make-a-ten#295]
Discovered during https://github.com/phetsims/number-play/issues/19, @chrisklus and I noticed that the plus sign overlaps the numbers:

![image](https://user-images.githubusercontent.com/679486/118691421-4c831a00-b7c6-11eb-9eb6-d10701c36571.png)

**Comment by chrisklus** [comment]
Closing, as a newer issue has been opened: https://github.com/phetsims/make-a-ten/issues/304
