### ISSUE TITLE
Bring smaller digits to front

### ISSUE THREAD

**Issue by bethstade** [phetsims/make-a-ten#39]
Smaller digits should default to front, even if a larger digit is moved over it.
Currently double and triple digit number can cover smaller digits and get "lost."
Singles always in front of double or triple digits.
Double digits always behind doubles, and in front of triples.
Triples always behind.
The original Snow Day has this logic.

**Comment by amanda-phet** [comment]
That means two numbers can get "added" if a 20 is placed over a 1 at the right spot. Is that the behavior you want?

**Comment by bethstade** [comment]
yes.  this is the behavior in the old snow day and it has not caused any issues.
This ensures that smaller numbers are never "lost."

----- Original Message -----From: Amanda McGarry <notifications@github.com>To: phetsims/making-tens <making-tens@noreply.github.com>Cc: bethstade <stadee@colorado.edu>Sent: Tue, 22 Sep 2015 18:35:31 -0000 (UTC)Subject: Re: [making-tens] Bring smaller digits to front (#39)

That means two numbers can get "added" if a 20 is placed over a 1 at the right spot. Is that the behavior you want?
&mdash;Reply to this email directly or view it on GitHub.

**Comment by bethstade** [comment]
Amanda, we can discuss about this if you want.
I thought it was a problem that the smaller numbers were hiding and this is an easy solution.


----- Original Message -----From: Amanda McGarry <notifications@github.com>To: phetsims/making-tens <making-tens@noreply.github.com>Cc: bethstade <stadee@colorado.edu>Sent: Tue, 22 Sep 2015 18:35:31 -0000 (UTC)Subject: Re: [making-tens] Bring smaller digits to front (#39)

That means two numbers can get "added" if a 20 is placed over a 1 at the right spot. Is that the behavior you want?
&mdash;Reply to this email directly or view it on GitHub.

**Comment by amanda-phet** [comment]
I don't have a problem with it- I was just making sure we were aware of a consequence!

**Comment by amanda-phet** [comment]
@AshrafSharf How is this issue coming along?

**Comment by amanda-phet** [comment]
After some further clarification from Beth, the behavior we are looking for is meant to avoid the possibility of a smaller number being hidden behind a larger number. 

There are two possibilities that we see making this work, so @AshrafSharf I think you can choose the simpler implementation. We do not have a preference. 

Option 1: If the user places a large number over a smaller one, then once that larger number is released the smaller one will move to the top layer and be visible in front of the larger number. 

Option 2: There are four layers and the smallest numbers are always the top-most layer, while the largest are always the bottom-most layer. This means a 100 being dragged in front of a 9 will actually be dragged "behind" the 9.

**Comment by AshrafSharf** [comment]
@amanda-phet  - I have used the option-1. Please let me know if this is fine

**Comment by amanda-phet** [comment]
This is looking good to me. We hadn't specified this, but I imagine the behavior should be consistent on all three screens, and right now it only seems implemented on the Explore screen.

**Comment by jonathanolson** [comment]
Seems to be implemented on all screens, although it won't occur if paper numbers are combined or repelled. Can you verify, and let me know if that's a problem?

**Comment by amanda-phet** [comment]
>it won't occur if paper numbers are combined or repelled. Can you verify, and let me know if that's a problem?

I'm not sure I understand what you mean here. Do you mean there are three behaviors when a small number is behind a large number: the small number comes forward, the two numbers combine, or the two numbers repel? 

That sounds about right. I can't think of a scenario where we want a different behavior.

**Comment by jonathanolson** [comment]
> Do you mean there are three behaviors when a small number is behind a large number: the small number comes forward, the two numbers combine, or the two numbers repel?

Yes, that's what happens when a number is dropped.

> That sounds about right. I can't think of a scenario where we want a different behavior.

Sounds good, will close this issue. Feel free to reopen or create another issue if we identify layering issues in future testing.
