### ISSUE TITLE
Add arrow cues to first number piece 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/make-a-ten#40]
The first time the user pulls out either 10 or 100, there are two arrow “instructions” that teach the user the two interactions. Once a user pulls out another piece or interacts with the sim in any way, the arrows will disappear. 

<img width="295" alt="screen shot 2015-09-28 at 9 20 38 am" src="https://cloud.githubusercontent.com/assets/7852916/10139864/35a4ac56-65c2-11e5-80a2-2269440e3ddb.png">

**Comment by amanda-phet** [comment]
@AshrafSharf How is this issue coming along?

**Comment by AshrafSharf** [comment]
@amanda-phet  I would like to discuss with you on skype for a few mins. I need some clarification on this requirement

**Comment by AshrafSharf** [comment]
Added the cues. Please let me know if the behaviour is fine.

**Comment by amanda-phet** [comment]
I noticed that the arrows didn't disappear unless I broke apart a number. If I simply moved the number, the arrows stayed visible (but lagged, which was also strange). 

What should happen is: if I interact in any way (such as pull out another number, interact with another number, move the number, or break apart the number) the arrows should disappear. 

Also, the arrows should only appear on 10 or 100. It doesn't make sense to use an arrow cue on a 1 since a 1 can not be broken apart.

**Comment by jonathanolson** [comment]
Also applied the above fix so the sim isn't erroring out in automated testing (arrowCueModel isn't available in the game screen).

**Comment by jonathanolson** [comment]
A few notes about the current cue behaviorial problems (@amanda-phet, correct me if I'm wrong about desired behavior):

(1) Dragging the number with the cues causes it to be disconnected from the cues:
![making-tens-cue-drag](https://cloud.githubusercontent.com/assets/480878/11483770/8a2fca22-9767-11e5-843c-65bb4061b801.png)
They should stay connected.

(2) Dragging a number (moving it, not pulling off) doesn't remove the "move" cue. The move cue should disappear (@amanda-phet, is this immediately on the start of the drag, or when they release?)

(3) Dragging a number back to the panel leaves its cues over the panel:
![making-tens-cue-panel](https://cloud.githubusercontent.com/assets/480878/11483796/bab63960-9767-11e5-96a8-a07cfa3b1f8e.PNG)
The cues should disappear then.

(4) Pulling a number off causes both cues to disappear (including the move cue). Only the "pull off" cue should disappear.

(5) Dragging out a new 100 from the panel will cause the cues to jump from the current number to the dragged-out number.
![making-tens-cue-swap-1](https://cloud.githubusercontent.com/assets/480878/11483871/2e78f572-9768-11e5-8024-023791107929.PNG)
![making-tens-cue-swap-2](https://cloud.githubusercontent.com/assets/480878/11483875/323f2564-9768-11e5-909d-05b939f139ba.PNG)
I believe cues shouldn't ever swap to a new number.

**Comment by amanda-phet** [comment]
(1) correct
(2) both cues should be removed
(3) correct
(4) both cues should be removed
(5) correct

**Comment by bethstade** [comment]
Cues should not disappear when numbers are added.  They should go away when the actions of pulling off or moving happen.  Right now, if I drag up a 100 in the explore screen, and then drag a 10 on top, the cues go away just form adding which should not happen.

**Comment by jonathanolson** [comment]
My current understanding is:
1. Only the first dragged out (10 or 100) number gets cues.
2. Both cues disappear whenever this number is (a) dragged back to the panel, (b) moved, or (c) split.
3. Cues stay with the number visually, and don't jump to new numbers added.

**Comment by bethstade** [comment]
There are 2 cues, one for splitting and one for moving.
If the number is just moved we want the split cue to remain.
Similarly, if it is split but not moved, we want the move cue to remain.
I believe ideally we would want the split cue to come back if the number is returned to the dock without splitting.

----- Original Message -----From: Jonathan Olson <notifications@github.com>To: phetsims/making-tens <making-tens@noreply.github.com>Cc: bethstade <stadee@colorado.edu>Sent: Wed, 17 Feb 2016 16:13:50 -0000 (UTC)Subject: Re: [making-tens] Add arrow cues to first number piece (#40)

My current understanding is:

1. Only the first dragged out (10 or 100) number gets cues.

2. Both cues disappear whenever this number is (a) dragged back to the panel, (b) moved, or (c) split.

3. Cues stay with the number visually, and don't jump to new numbers added.
&mdash;Reply to this email directly or view it on GitHub.

**Comment by jonathanolson** [comment]
> If the number is just moved we want the split cue to remain.
> Similarly, if it is split but not moved, we want the move cue to remain.

I agree with that, but it goes against @amanda-phet's recommendation above (https://github.com/phetsims/making-tens/issues/40#issuecomment-160757040) that "both cues should be removed", for both the "moved" and "split" actions.

**Comment by bethstade** [comment]
I am pretty sure we discussed this in a meeting since she made that comment.
I will look in the meeting notes and see if we made note of it.

----- Original Message -----From: Jonathan Olson <notifications@github.com>To: phetsims/making-tens <making-tens@noreply.github.com>Cc: bethstade <stadee@colorado.edu>Sent: Wed, 17 Feb 2016 18:36:08 -0000 (UTC)Subject: Re: [making-tens] Add arrow cues to first number piece (#40)


If the number is just moved we want the split cue to remain.

Similarly, if it is split but not moved, we want the move cue to remain.

I agree with that, but it goes against @amanda-phet's recommendation above (#40 (comment)) that "both cues should be removed", for both the "moved" and "split" actions.
&mdash;Reply to this email directly or view it on GitHub.

**Comment by bethstade** [comment]
I can't a meeting note about when we discussed it,  but I do believe it is correct to treat the 2 cues as separate actions so the user is aware of BOTH actions.  You only get one chance so I think it is important that you get to experience both actions.  The correct action should be:
"If the number is just moved we want the split cue to remain.
Similarly, if it is split but not moved, we want the move cue to remain."

**Comment by jonathanolson** [comment]
Additionally (@amanda-phet and @bethstade), the cues currently fade away. Is that helpful (over them instantly disappearing? I didn't see it mentioned anywhere in this discussion.

**Comment by bethstade** [comment]
I like fade over disappear.

**Comment by jonathanolson** [comment]
I'm waiting to code-review the related code until the above problems are resolved.

**Comment by amanda-phet** [comment]
We plan to make changes to the arrow cues so please wait to make any further changes to the behavior of these arrows.

**Comment by jonathanolson** [comment]
Will handle cue issues in #231.
