### ISSUE TITLE
Level selection buttons should not have text

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/make-a-ten#51]
I thought there was already an open issue about this. The level selection buttons should only have artwork and should not have any text. @bethstade is writing a one sentence description of each level that will be listed under an info button. 

<img width="682" alt="screen shot 2015-11-30 at 1 44 30 pm" src="https://cloud.githubusercontent.com/assets/7852916/11483931/84a37148-9768-11e5-9db2-bbda96ba66c3.png">

**Comment by bethstade** [comment]
The one sentence descriptions are on page 16 of the Google.
I have question about the image for the triple digits.
The whole point of Making Tens is to see numbers as their component parts, 100's, 10's, and 1's.
I do love the juggling image BUT the idea of thinking of triple digits as 3 different numbers is completely at odds with the point of Making Tens.
Do we have an alternative image for triple digits?
thanks,
Beth

----- Original Message -----From: Amanda McGarry <notifications@github.com>To: phetsims/making-tens <making-tens@noreply.github.com>Cc: bethstade <stadee@colorado.edu>Sent: Mon, 30 Nov 2015 20:45:13 -0000 (UTC)Subject: [making-tens] Level selection buttons should not have text (#51)

I thought there was already an open issue about this. The level selection buttons should only have artwork and should not have any text. @bethstade is writing a one sentence description of each level that will be listed under an info button.

&mdash;Reply to this email directly or view it on GitHub.

**Comment by bethstade** [comment]
Perhaps for the triple digits the PHet girl could juggle a 400, a 50 and an 8?

----- Original Message -----From: Amanda McGarry <notifications@github.com>To: phetsims/making-tens <making-tens@noreply.github.com>Cc: bethstade <stadee@colorado.edu>Sent: Mon, 30 Nov 2015 20:45:13 -0000 (UTC)Subject: [making-tens] Level selection buttons should not have text (#51)

I thought there was already an open issue about this. The level selection buttons should only have artwork and should not have any text. @bethstade is writing a one sentence description of each level that will be listed under an info button.

&mdash;Reply to this email directly or view it on GitHub.

**Comment by amanda-phet** [comment]
The images haven't changed in the last 2 months, but I can probably make the change you are requesting since it seems minor. I'll have a mockup for the next design meeting.

**Comment by amanda-phet** [comment]
Updated level selection icons have been emailed to @jonathanolson but I will keep this issue open to resolve the issue with text on the buttons.

**Comment by jonathanolson** [comment]
Reassigning, since I'm not sure what to do with the one-sentence descriptions / info button.

**Comment by amanda-phet** [comment]
The goal is to communicate the content of the levels in words, rather than images. When the user clicks on the info button, they should get a dialog popup that looks something like this:

<img width="684" alt="screen shot 2016-01-29 at 4 24 13 pm" src="https://cloud.githubusercontent.com/assets/7852916/12690968/cedc58e0-c6a4-11e5-8f8e-dcb68d898e8c.png">

The level descriptions are in the design doc here: https://docs.google.com/document/d/1Na-ITlFbflngxxVxFJ_lHdTCGuTmBb2YPTjhZ8A4d2U/edit#heading=h.1z6pkazd4ksl

**Comment by jonathanolson** [comment]
@ariel-phet as this is marked as a change request, should I be the one implementing this?

**Comment by ariel-phet** [comment]
@jonathanolson no - the things marked change request were for @AshrafSharf and were negotiated with him some time ago

**Comment by ariel-phet** [comment]
@jonathanolson actually correction...it looks like Amanda deemed this one for you, leaving the assignment with you. That is mixing the labels a bit, so I am going to change the label to enhancement.

**Comment by jonathanolson** [comment]
@bethstade, is this info button only visible on the "select level" part of the game screen?

**Comment by bethstade** [comment]
Yes, this is only a feature in the select level part of the game screen.

**Comment by jonathanolson** [comment]
Also assuming typo fixes:

- "Add single digit numbers to **gets** sums of 10 and under." to "Add single digit numbers to **get** sums of 10 and under."
- "Add hundreds and **multiplies** of ten." to "Add hundreds and **multiples** of ten."

**Comment by jonathanolson** [comment]
Implemented:

![make-a-ten-dialog-1](https://cloud.githubusercontent.com/assets/480878/19460569/131f2a14-949a-11e6-92b5-e650d9d6a844.PNG)

Let me know if anything should be improved.

**Comment by bethstade** [comment]
yes. thank you.

----- Original Message -----From: Jonathan Olson <notifications@github.com>To: phetsims/make-a-ten <make-a-ten@noreply.github.com>Cc: bethstade <stadee@colorado.edu>, Assign <assign@noreply.github.com>Sent: Tue, 18 Oct 2016 00:27:40 -0000 (UTC)Subject: Re: [phetsims/make-a-ten] Level selection buttons should not have text (#51)

Also assuming typo fixes:

"Add single digit numbers to gets sums of 10 and under." to "Add single digit numbers to get sums of 10 and under."
"Add hundreds and multiplies of ten." to "Add hundreds and multiples of ten."

&mdash;You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by bethstade** [comment]
Looks good to me. Amanda?

**Comment by amanda-phet** [comment]
Looks great!
