### ISSUE TITLE
[review] Model knowledge of viewPortBounds and screenBounds

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/make-a-ten#60]
I don't see documentation about why we store viewPortBounds OR screenBounds in MakingTensCommonModel.

Why do we need two different bounds? Presumably we'd only need one bounds that relates to the screen's size (as we need one to reposition the numbers when the bounds change).

**Comment by AshrafSharf** [comment]
This screenbounds was used for randomly placing the PaperNumbers on Game screen and Adding-Numbers screen. The code has been refactored to use constants

**Comment by jonathanolson** [comment]
Looks better. After reading more of the code, it looks like there are many places where the screen view's availableViewBoundsProperty is being used to modify paper model locations (from view code).

I'd recommend that viewPortBounds be used instead (renamed as something like availableModelBounds, as the model doesn't know about the view), and that it would be a property (declared in the PropertySet super call).

This way, all the view has to do is update the model's availableModelBounds (instead of digging into the model and changing paper model positions), and the model would be able to constrain the positions and update as necessary.

Thoughts? Will be available to discuss tomorrow.
