### ISSUE TITLE
Duplication in ProgressIndicatorLabelNode

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/make-a-ten#80]
Looks very similar to Vegas' ProgressIndcator, but might be missing some bugfixes to the Vegas version (like checking ```remainder > 1E-6```?).

What are the differences, and reasons for a separate type?

**Comment by jonathanolson** [comment]
The sim-specific one has additional text, and doesn't show empty stars unless there is no star (with no concept of a perfect score).

@samreid or @jbphet, I'd love an opinion on whether this behavior should be included in the Vegas type, or whether we should just refactor a sub-component out that displays M empty stars and N full stars (with possible fractions) that is used by both.

**Comment by samreid** [comment]
> a sub-component out that displays M empty stars and N full stars (with possible fractions) that is used by both.

This sounds best to me.

**Comment by jbphet** [comment]
The sub-component idea also seems preferable to me.  So far, the Making Tens behavior is pretty unique, no need to fold it into the common code unless we think it is going to be used again anywhere.
