### ISSUE TITLE
Duplication of LevelSelectionButton

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/make-a-ten#81]
Seems very similar to Vegas' LevelSelectionButton.

What is the reason for having the duplicated code?

**Comment by jonathanolson** [comment]
If we need the duplication, I'll have more comments on file contents (e.g. removing time-related things, etc.)

**Comment by jonathanolson** [comment]
@pixelzoom noted documentation that I missed:
```js
* The Vegas LevelSelectionButton is copied over to MakingTens, because of the need to display
* the score in "Text", next  to the star symbol.
```
in https://github.com/phetsims/making-tens/issues/108#issuecomment-190537691.

See https://github.com/phetsims/making-tens/issues/108#issuecomment-190537691 and https://github.com/phetsims/making-tens/issues/108#issuecomment-190553537 for discussion.

**Comment by samreid** [comment]
I noticed this as well, out of the 158 lines of code, about 138 of them are exact duplicates.  We should generalize LevelSelectionButton so that it can be efficiently reused, or just let the simulation use the vegas defaults.

**Comment by samreid** [comment]
I'll be working on https://github.com/phetsims/vegas/issues/49 soon, and will likely change the vegas LevelSelectionButton.js
